#!/usr/bin/env python3
"""Build the arXiv edition of the manuscript from ``manuscript/main.tex``.

The arXiv preprint is a *derivative* of the JSS submission, not a fork:
this script reads the live ``main.tex``, applies a short list of
arXiv-specific edits, flattens every file the manuscript actually pulls in
into one directory, compiles it, and writes

* ``build/arxiv/statspai-arxiv-src.tar.gz`` -- the upload for arXiv
  (``.tex`` + ``jss.cls`` + ``jss.bst`` + the compiled ``.bbl`` + figures
  and tables; no ``.bib``, arXiv does not run BibTeX), and
* ``build/arxiv/statspai-arxiv.pdf`` -- the PDF arXiv should reproduce, and
* ``build/arxiv/arxiv-metadata.txt`` -- title, comments, categories, licence
  and the plain-text abstract for the submission form.

The arXiv edits, and why each one exists:

* ``\\pdfoutput=1`` on the first line, so arXiv's AutoTeX runs pdfLaTeX
  (the figures are PDF).
* ``\\documentclass[article,nojss]{jss}`` -- ``nojss`` drops the JSS
  masthead, logo, volume/issue line and DOI footer. A preprint set with
  the journal masthead reads as a published JSS article, which it is not.
* ``thumbpdf`` is dropped: it wants a ``thumbpdf.tex`` generated by an
  external run and only produces a warning without one.
* A title footnote stating that the article is a preprint submitted to
  JSS, the release it describes, and where replication materials live.
* ``../replication/tables/*.tex`` inputs are rewritten into the flat tree.

Each text edit must match exactly once; a ``main.tex`` change that makes
an edit stop matching fails the build rather than silently shipping an
unedited preprint.

After packaging, the tarball is unpacked into a fresh directory and
compiled with pdfLaTeX alone (no BibTeX), as arXiv does, and the log is
checked for undefined references and citations.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

from _paths import PAPER_ROOT  # noqa: E402

MANUSCRIPT = PAPER_ROOT / "manuscript"
OUT_DIR = PAPER_ROOT / "build" / "arxiv"
STAGE = OUT_DIR / "src"
CHECK = OUT_DIR / "compile-check"
TARBALL = OUT_DIR / "statspai-arxiv-src.tar.gz"
PDF_OUT = OUT_DIR / "statspai-arxiv.pdf"
METADATA = OUT_DIR / "arxiv-metadata.txt"
#: arXiv's submission form caps the abstract at 1,920 characters.
ARXIV_ABSTRACT_MAX = 1920
#: Shortenings applied to the *form* abstract only, and only when the PDF
#: abstract exceeds the cap. The typeset abstract in the preprint is the
#: JSS one, unchanged. Each edit must match exactly once.
FORM_ABSTRACT_EDITS = (
    (", and none call the reference they are compared against)",
     ", none call their reference)"),
)
SOURCE_DATE_EPOCH = int(os.environ.get("SOURCE_DATE_EPOCH", "1780185600"))

#: Where a reader of the preprint can obtain the replication materials.
#: The Paper-JSS repository is private, so the default does not point at
#: it; override with --replication-note once a public archive (e.g. a
#: Zenodo DOI) exists.
DEFAULT_REPLICATION_NOTE = (
    "Paths of the form \\texttt{Paper-JSS/\\ldots} refer to the replication "
    "package submitted with the manuscript; it is available from the "
    "corresponding author on request."
)

INPUT_RE = re.compile(r"\\input\{([^}]+)\}")
GRAPHICS_RE = re.compile(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}")
COMMENT_RE = re.compile(r"(?<!\\)%.*")


def _edits(replication_note: str) -> list[tuple[str, str]]:
    footnote = (
        "\\thanks{Preprint. This article has been submitted to the "
        "\\emph{Journal of Statistical Software}; it describes "
        "\\pkg{StatsPAI} release \\StatsPAIVersion{}. " + replication_note + "}"
    )
    return [
        ("\n\\documentclass[article]{jss}\n",
         "\n\\pdfoutput=1\n\\documentclass[article,nojss]{jss}\n"),
        ("\\usepackage{orcidlink,thumbpdf,lmodern}",
         "\\usepackage{orcidlink,lmodern}"),
        ("       Causal Inference}\n\\Plaintitle",
         "       Causal Inference" + footnote + "}\n\\Plaintitle"),
    ]


def _strip_comments(text: str) -> str:
    return "\n".join(COMMENT_RE.sub("", line) for line in text.splitlines())


def _flat_name(ref: str) -> str:
    """Map a manuscript-relative input path to its path in the flat tree."""
    return ref.replace("../replication/tables/", "replication-tables/")


def _collect(tex: Path, found: dict[str, Path]) -> None:
    """Record every \\input and \\includegraphics reachable from ``tex``."""
    body = _strip_comments(tex.read_text(encoding="utf-8"))
    for ref in INPUT_RE.findall(body):
        name = ref if ref.endswith(".tex") else ref + ".tex"
        src = (MANUSCRIPT / name).resolve()
        if not src.is_file():
            sys.exit(f"FAIL -- {tex.name} inputs {ref}, which does not exist")
        if name not in found:
            found[name] = src
            _collect(src, found)
    for ref in GRAPHICS_RE.findall(body):
        src = (MANUSCRIPT / ref).resolve()
        if not src.is_file():
            sys.exit(f"FAIL -- {tex.name} includes graphic {ref}, which does not exist")
        found.setdefault(ref, src)


def _rewrite_inputs(text: str) -> str:
    return text.replace("{../replication/tables/", "{replication-tables/")


def _run(cmd: list[str], cwd: Path) -> None:
    env = dict(os.environ, SOURCE_DATE_EPOCH=str(SOURCE_DATE_EPOCH), FORCE_SOURCE_DATE="1")
    proc = subprocess.run(cmd, cwd=cwd, env=env, capture_output=True, text=True)
    if proc.returncode != 0:
        tail = "\n".join((proc.stdout + proc.stderr).splitlines()[-40:])
        sys.exit(f"FAIL -- {' '.join(cmd)} in {cwd}:\n{tail}")


def _check_log(log: Path) -> None:
    text = log.read_text(encoding="utf-8", errors="replace")
    problems = [
        line for line in text.splitlines()
        if re.search(r"undefined (references|citations)|Citation .* undefined|"
                     r"Reference .* undefined|There were undefined", line)
    ]
    if problems:
        sys.exit(f"FAIL -- {log} reports unresolved references:\n" + "\n".join(problems[:20]))


def _write_metadata(pages: int) -> int:
    """Write the plain-text fields the arXiv submission form asks for.

    The LaTeX abstract is built from generated count macros, so its text
    is taken from the compiled PDF rather than from the source.
    """
    text = subprocess.run(["pdftotext", "-l", "1", str(PDF_OUT), "-"],
                          capture_output=True, text=True, check=True).stdout
    match = re.search(r"Abstract\s*(.*?)\s*Keywords:", text, re.S)
    if not match:
        sys.exit("FAIL -- could not locate the abstract on page 1 of the arXiv PDF")
    abstract = re.sub(r"-\n(?=[a-z])", "-", match.group(1))
    abstract = re.sub(r"\s+", " ", abstract).strip()
    abstract = abstract.translate(str.maketrans({"\u2019": "'", "\u2018": "'",
                                                 "\u201c": '"', "\u201d": '"'}))
    if len(abstract) > ARXIV_ABSTRACT_MAX:
        for old, new in FORM_ABSTRACT_EDITS:
            if abstract.count(old) != 1:
                sys.exit(f"FAIL -- form-abstract edit no longer matches once: {old!r}")
            abstract = abstract.replace(old, new)
    if len(abstract) > ARXIV_ABSTRACT_MAX:
        sys.exit(f"FAIL -- abstract is {len(abstract)} characters; arXiv allows "
                 f"{ARXIV_ABSTRACT_MAX}")
    METADATA.write_text(
        "Title: StatsPAI: Validation-Tiered Python Workflows for Causal Inference\n"
        "Authors: Biaoyue Wang, Scott Rozelle\n"
        f"Comments: {pages} pages. Submitted to the Journal of Statistical Software. "
        "Software: https://github.com/brycewang-stanford/StatsPAI\n"
        "Primary category: stat.CO\n"
        "Cross-list: econ.EM, stat.ME\n"
        "License: CC BY 4.0\n\n"
        f"Abstract ({len(abstract)} characters):\n{abstract}\n",
        encoding="utf-8",
    )
    return len(abstract)


def build(replication_note: str) -> None:
    main_src = MANUSCRIPT / "main.tex"
    main = main_src.read_text(encoding="utf-8")
    for old, new in _edits(replication_note):
        count = main.count(old)
        if count != 1:
            sys.exit(f"FAIL -- arXiv edit expected exactly one match in main.tex, "
                     f"found {count}: {old!r}")
        main = main.replace(old, new)

    found: dict[str, Path] = {}
    _collect(main_src, found)

    shutil.rmtree(OUT_DIR, ignore_errors=True)
    STAGE.mkdir(parents=True)
    (STAGE / "main.tex").write_text(_rewrite_inputs(main), encoding="utf-8")
    for name, src in sorted(found.items()):
        dest = STAGE / _flat_name(name)
        dest.parent.mkdir(parents=True, exist_ok=True)
        if name.endswith(".tex"):
            dest.write_text(_rewrite_inputs(src.read_text(encoding="utf-8")), encoding="utf-8")
        else:
            shutil.copy2(src, dest)
    for support in ("jss.cls", "jss.bst", "jss-bib.bib"):
        shutil.copy2(MANUSCRIPT / support, STAGE / support)

    # Full compile (with BibTeX) to produce the .bbl arXiv needs.
    _run(["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", "main.tex"], STAGE)
    _check_log(STAGE / "main.log")

    shipped = ["main.tex", "main.bbl", "jss.cls", "jss.bst"] + sorted(
        _flat_name(name) for name in found
    )
    with tarfile.open(TARBALL, "w:gz") as tar:
        for rel in shipped:
            info = tar.gettarinfo(str(STAGE / rel), arcname=rel)
            info.mtime = SOURCE_DATE_EPOCH
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            with open(STAGE / rel, "rb") as fh:
                tar.addfile(info, fh)
    shutil.copy2(STAGE / "main.pdf", PDF_OUT)

    # Recompile from the tarball alone, the way arXiv does: pdfLaTeX only,
    # no BibTeX, no .bib in the tree.
    CHECK.mkdir()
    with tarfile.open(TARBALL, "r:gz") as tar:
        tar.extractall(CHECK)
    for _ in range(3):
        _run(["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "main.tex"], CHECK)
    _check_log(CHECK / "main.log")

    info = subprocess.run(["pdfinfo", str(PDF_OUT)], capture_output=True,
                          text=True, check=True).stdout
    pages = int(re.search(r"Pages:\s+(\d+)", info).group(1))
    abstract_chars = _write_metadata(pages)

    size_mb = TARBALL.stat().st_size / 1e6
    print(f"arXiv source: {TARBALL.relative_to(PAPER_ROOT)} "
          f"({len(shipped)} files, {size_mb:.2f} MB)")
    print(f"arXiv PDF:    {PDF_OUT.relative_to(PAPER_ROOT)}")
    print(f"Metadata:     {METADATA.relative_to(PAPER_ROOT)} "
          f"(abstract {abstract_chars}/{ARXIV_ABSTRACT_MAX} characters)")
    print("Tarball recompiles with pdfLaTeX alone and no unresolved references.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--replication-note", default=DEFAULT_REPLICATION_NOTE,
                        help="LaTeX sentence(s) telling preprint readers where the "
                             "replication materials are.")
    args = parser.parse_args()
    build(args.replication_note)


if __name__ == "__main__":
    main()
