r"""Generate Appendix C's worked schema example.

Writes manuscript/tables/appendix_c_schema.tex with the live JSON
output of sp.function_schema("callaway_santanna"). Re-run when the
schema changes:

    python Paper-JSS/replication/scripts/gen_appendix_C.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import statspai as sp
from statspai import registry as reg

# The archive ships source files ASCII-transliterated (JSS: "Source code must
# be submitted in ASCII files"), which also rewrites the descriptions this
# schema carries. Normalising with the same function (StatsPAI's
# scripts/ascii_source.py, idempotent on ASCII) makes the listing
# byte-identical whether it is rebuilt from the repository or the archive.
sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "scripts"))
from ascii_source import ascii_source_text  # noqa: E402


HERE = Path(__file__).resolve().parent
OUT = HERE.parent.parent / "manuscript" / "tables" / "appendix_c_schema.tex"


def main() -> None:
    schema = reg.function_schema("callaway_santanna")
    text = ascii_source_text(json.dumps(schema, indent=2, ensure_ascii=False))
    version = getattr(sp, "__version__", "unknown")
    content = (
        "% AUTO-GENERATED by replication/scripts/gen_appendix_C.py\n"
        f"% Source: sp.function_schema('callaway_santanna') at v{version}.\n"
        "\\begin{lstlisting}[language=,basicstyle=\\ttfamily\\scriptsize,\n"
        "                   frame=single,framesep=4pt,framerule=0pt,\n"
        "                   backgroundcolor=\\color{codebg!60!white},\n"
        "                   breaklines=true,\n"
        "                   caption={Live JSON schema emitted by\n"
        "                   \\code{sp.function\\_schema(\"callaway\\_santanna\")}\n"
        f"                   at \\statspai{{}} {version} ({len(text):,} characters,\n"
        "                   verbatim up to the archive's ASCII transliteration).}]\n"
        f"{text}\n"
        "\\end{lstlisting}\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"OK -- wrote {OUT} ({len(text)} chars of JSON)")


if __name__ == "__main__":
    main()
