r"""Generate Appendix A's function inventory longtable from the live
StatsPAI registry. Writes manuscript/tables/appendix_a_inventory.tex.

This is the source of truth for the per-category counts in
Appendix A. Re-run whenever the registry changes:

    python Paper-JSS/replication/scripts/gen_appendix_A.py
"""
from __future__ import annotations

import re
import unicodedata
from collections import Counter
from pathlib import Path

import statspai as sp
from statspai import registry as reg
from statspai.help import CATEGORY_DESCRIPTIONS


HERE = Path(__file__).resolve().parent
TABLES_DIR = HERE.parent.parent / "manuscript" / "tables"


def latex_escape(value: object) -> str:
    text = "" if value is None else str(value)
    text = (
        text.replace("—", "-")
        .replace("–", "-")
        .replace("’", "'")
        .replace("“", '"')
        .replace("”", '"')
    )
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")
    text = re.sub(r"\s+", " ", text).strip()
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def collect_counts() -> Counter:
    counts: Counter = Counter()
    for name in sp.list_functions():
        info = reg.describe_function(name)
        cat = (info or {}).get("category") or "other"
        counts[cat] += 1
    return counts


def render_longtable(counts: Counter) -> str:
    descriptions = dict(CATEGORY_DESCRIPTIONS)
    rows = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    total = sum(counts.values())
    version = getattr(sp, "__version__", "unknown")

    body = []
    for cat, n in rows:
        gloss = latex_escape(descriptions.get(cat, ""))
        body.append(f"\\code{{{latex_escape(cat)}}} & {n} & {gloss} \\\\")

    rows_tex = "\n".join(body)
    return (
        "% AUTO-GENERATED by replication/scripts/gen_appendix_A.py\n"
        "% Do not hand-edit; re-run the script when the registry changes.\n"
        "\\begin{longtable}{@{}p{0.21\\linewidth}rp{0.59\\linewidth}@{}}\n"
        f"\\caption{{Public functions per category at \\statspai{{}} {version},\n"
        "  generated from the live registry. Total: "
        f"{total} public functions across {len(rows)} categories.\n"
        "  Category descriptions are taken from\n"
        "  \\code{statspai.help.CATEGORY\\_DESCRIPTIONS}.}\n"
        "\\label{tab:inventory}\\\\\n"
        "\\toprule\n"
        "Category & \\#\\ funcs & Description \\\\\n"
        "\\midrule\n"
        "\\endfirsthead\n"
        "\\multicolumn{3}{c}{\\textit{(continued)}} \\\\\n"
        "\\toprule\n"
        "Category & \\#\\ funcs & Description \\\\\n"
        "\\midrule\n"
        "\\endhead\n"
        "\\midrule\n"
        f"\\textbf{{Total}} & \\textbf{{{total}}} & "
        f"across \\textbf{{{len(rows)}}} categories \\\\\n"
        "\\bottomrule\n"
        "\\endlastfoot\n"
        f"{rows_tex}\n"
        "\\end{longtable}\n"
    )


def main() -> None:
    counts = collect_counts()
    tex = render_longtable(counts)
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    out = TABLES_DIR / "appendix_a_inventory.tex"
    out.write_text(tex, encoding="utf-8")
    print(f"OK -- wrote {out} ({sum(counts.values())} funcs / {len(counts)} cats)")


if __name__ == "__main__":
    main()
