#!/usr/bin/env python3
"""Generate the seed-replicated causal-forest table (Section 5, T3).

Reads the frozen seed-replication fixtures written by
``tests/reference_parity/_fixtures/_generate_grf_seed_mc_{R.R,py.py}`` and
writes ``manuscript/tables/forest_seed_mc.tex``. The equivalence verdicts
printed here are the ones ``tests/reference_parity/
test_grf_seed_mc_equivalence.py`` asserts.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

from _paths import PAPER_ROOT, statspai_root  # noqa: E402

FIX = statspai_root() / "tests" / "reference_parity" / "_fixtures"
OUT = PAPER_ROOT / "manuscript" / "tables" / "forest_seed_mc.tex"
DATASETS = (
    ("Reference fixture", "grf_seed_mc_py.json", "grf_seed_mc_R.json"),
    ("Module-13 design", "grf_seed_mc_m13_py.json", "grf_seed_mc_m13_R.json"),
)
TREES = ("trees_500", "trees_2000", "trees_8000")
DELTA = 0.1
Z_TOST = 1.6448536269514722


def _sci(x: float) -> str:
    if x == 0:
        return "0"
    exp = int(np.floor(np.log10(abs(x))))
    mant = x / 10**exp
    return f"\\({mant:.1f}\\times10^{{{exp}}}\\)"


def rows() -> list[str]:
    out = []
    for label, py_file, r_file in DATASETS:
        py = json.loads((FIX / py_file).read_text(encoding="utf-8"))
        r = json.loads((FIX / r_file).read_text(encoding="utf-8"))
        for i, trees in enumerate(TREES):
            p = np.array([row["ate"] for row in py[trees]])
            q = np.array([row["ate"] for row in r[trees]])
            gap = p.mean() - q.mean()
            se = np.sqrt(p.var(ddof=1) / p.size + q.var(ddof=1) / q.size)
            samp = float(np.mean([row["ate_se"] for row in r[trees]]))
            equiv = abs(gap) + Z_TOST * se < DELTA * samp
            first = label if i == 0 else ""
            verdict = "yes" if equiv else "\\textbf{no}"
            out.append(
                f"{first} & {trees.split('_')[1]} & {p.size}/{q.size} & "
                f"{gap:+.5f} & {_sci(se)} & {gap / samp:+.3f} & "
                f"{_sci(p.std(ddof=1))} & {_sci(q.std(ddof=1))} & "
                f"{verdict} \\\\"
            )
    return out


def render() -> str:
    body = "\n".join(rows())
    return (
        "% AUTO-GENERATED by replication/scripts/generate_forest_seed_table.py\n"
        "\\begingroup\\setlength{\\tabcolsep}{3pt}\n"
        "\\begin{tabular}{@{}lrrrrrrrl@{}}\n"
        "\\toprule\n"
        "Data & Trees & Seeds & Gap & MC SE & Gap/SE\\(_s\\) & "
        "SD\\(_{\\mathrm{MC}}\\) (\\statspai{}) & SD\\(_{\\mathrm{MC}}\\) (\\pkg{grf}) & Equiv. \\\\\n"
        "\\midrule\n"
        f"{body}\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\endgroup\n"
    )


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"STALE -- {OUT.relative_to(PAPER_ROOT)}; run without --check")
            return 1
        print(f"OK -- {OUT.relative_to(PAPER_ROOT)} is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(PAPER_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
