"""Generate the full registry inventory appendix table."""
from __future__ import annotations

import re
import unicodedata
from pathlib import Path

import statspai as sp
import statspai.registry as registry


HERE = Path(__file__).resolve().parent
PAPER_DIR = HERE.parents[1]
TABLE_DIR = PAPER_DIR / "manuscript" / "tables"
OUT = TABLE_DIR / "function_inventory_full.tex"


def _latex_escape(value: object, max_len: int | None = None) -> str:
    text = "" if value is None else str(value)
    text = (
        text.replace("ρ", "rho")
        .replace("β", "beta")
        .replace("ε", "epsilon")
        .replace("λ", "lambda")
        .replace("θ", "theta")
        .replace("τ", "tau")
        .replace("Δ", "Delta")
        .replace("δ", "delta")
        .replace("σ", "sigma")
        .replace("×", "x")
        .replace("≡", "=")
        .replace("∈", "in")
        .replace("≤", "<=")
        .replace("≥", ">=")
        .replace("agent-native", "agent-facing")
        .replace("–", "-")
        .replace("—", "-")
        .replace("’", "'")
        .replace("“", '"')
        .replace("”", '"')
    )
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")
    text = re.sub(r"\s+", " ", text).strip()
    if max_len is not None and len(text) > max_len:
        text = text[: max_len - 3].rstrip() + "..."
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def _latex_identifier(value: object) -> str:
    escaped = _latex_escape(value)
    escaped = escaped.replace(r"\_", r"\_\allowbreak{}")
    return escaped


def build_table() -> str:
    registry._ensure_full_registry()
    version = getattr(sp, "__version__", "unknown")
    specs = sorted(
        registry._REGISTRY.values(),
        key=lambda spec: (spec.category, spec.name),
    )
    rows = []
    for spec in specs:
        rows.append(
            "    "
            + " & ".join(
                [
                    r"\texttt{" + _latex_identifier(spec.name) + "}",
                    _latex_escape(spec.category, 32),
                    _latex_escape(spec.description, 120),
                ]
            )
            + r" \\"
        )
    body = "\n".join(rows)
    return (
        "% Generated by replication/scripts/generate_inventory.py; do not edit by hand.\n"
        "\\begingroup\n"
        "\\scriptsize\n"
        "\\setlength{\\LTleft}{0pt}\n"
        "\\setlength{\\LTright}{0pt}\n"
        "\\begin{longtable}{p{0.24\\textwidth}p{0.14\\textwidth}p{0.54\\textwidth}}\n"
        f"\\caption{{Full public function inventory at \\statspai{{}} {version}.}}\\label{{tab:function-inventory-full}}\\\\\n"
        "\\toprule\n"
        "Function & Category & Description \\\\\n"
        "\\midrule\n"
        "\\endfirsthead\n"
        "\\toprule\n"
        "Function & Category & Description \\\\\n"
        "\\midrule\n"
        "\\endhead\n"
        "\\midrule\n"
        "\\multicolumn{3}{r}{Continued on next page}\\\\\n"
        "\\endfoot\n"
        "\\bottomrule\n"
        "\\endlastfoot\n"
        f"{body}\n"
        "\\end{longtable}\n"
        "\\endgroup\n"
    )


def main() -> int:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_table(), encoding="utf-8")
    print(f"OK -- wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
