"""Generate the manuscript's headline original-data parity table.

The table (``manuscript/tables/headline_parity.tex``) was previously
hand-written, which is exactly how a replica number can silently stand
in for an original-data number. This generator materializes every cell
from ``tests/orig_parity/results/*.json`` -- the same artifacts checked
by ``tests/orig_parity/compare_orig.py`` -- so a stale or transplanted
number fails the manuscript artifact audit instead of reaching print.

Usage:
    python generate_headline_parity_table.py           # write the .tex
    python generate_headline_parity_table.py --check   # drift guard
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _paths import PAPER_ROOT, STATSPAI_ROOT  # noqa: E402

ORIG_RESULTS = STATSPAI_ROOT / "tests" / "orig_parity" / "results"
OUT_TEX = PAPER_ROOT / "manuscript" / "tables" / "headline_parity.tex"

HEADER = "% AUTO-GENERATED by replication/scripts/generate_headline_parity_table.py\n"

# (module, statistic, extract label, statistic label, published fmt,
#  value fmt, extra note or None)
ROWS = [
    ("01_card_original", "ols_beta_educ",
     r"\code{wooldridge::card}", "OLS educ", "%.3f", "%.5f", None),
    ("01_card_original", "iv_beta_educ_nearc4",
     r"\code{wooldridge::card}", "2SLS educ", "%.3f", "%.4f", None),
    ("02_mpdta_original", "simple_ATT",
     r"\code{did::mpdta}", "CS simple ATT", "%.4f", "%.5f",
     "no printed vignette anchor"),
    ("02_mpdta_original", "dynamic_overall_ATT",
     r"\code{did::mpdta}", "CS dynamic overall ATT", "%.4f", "%.5f",
     "vignette prints $-0.0772$"),
    ("03_basque_original", "avg_post_gap",
     r"\code{Synth::basque}", "ADH avg gap", "%.3f", "%.4f",
     "STATA_NOTE"),
    ("05_lee_original", "rd_jump_robust",
     r"\code{rdrobust::RDsenate}", "robust RD jump", "%.3f", "%.3f",
     r'\code{bwselect="cct"} path'),
    ("04b_nsw_psid_original", "adj_ols_att",
     r"\code{causalsens::lalonde.psid}", "adjusted OLS ATT", "%.0f", "%.1f",
     "public composite extract"),
    ("06_nhefs_ch12_ipw", "ipw_att",
     r"NHEFS (\emph{What If})", "IP-weighted ATE", "%.1f", "%.3f", None),
    ("07_nhefs_ch13_gformula", "gformula_ate",
     r"NHEFS (\emph{What If})", "g-formula ATE", "%.1f", "%.3f", None),
]


def _row_map(module: str, side: str) -> dict[str, dict]:
    path = ORIG_RESULTS / f"{module}_{side}.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    return {r["statistic"]: r for r in payload["rows"]}


def _sci(x: float) -> str:
    """LaTeX scientific notation like 7.9\\times10^{-15}."""
    if x == 0:
        return "0"
    exp = math.floor(math.log10(abs(x)))
    mant = x / 10**exp
    return rf"{mant:.1f}\times10^{{{exp}}}"


def build_table() -> str:
    lines = [
        HEADER
        + "% Cells come from tests/orig_parity/results/*.json; do not hand edit.",
        # L{} is main.tex's ragged-right p-column. Justified p-columns
        # stretch a short note such as "rel(sp,R) 3.5 $\times$ 10^{-16}"
        # across the full column, which reads as four separate tokens.
        r"\begin{tabular}{@{}L{0.24\linewidth}L{0.19\linewidth}rrrL{0.23\linewidth}@{}}",
        r"\toprule",
        r"Extract & Statistic & Published & \statspai{} & \proglang{R} & Note \\",
        r"\midrule",
    ]
    for module, stat, extract, stat_label, pub_fmt, val_fmt, note in ROWS:
        py = _row_map(module, "py")[stat]
        rr = _row_map(module, "R")[stat]
        sp_est = float(py["estimate"])
        r_est = float(rr["estimate"])
        rel = abs(sp_est - r_est) / abs(r_est) if r_est != 0 else float("nan")
        pub = py.get("published")
        pub_cell = ("$" + pub_fmt % float(pub) + "$") if pub is not None else "--"
        rel_txt = rf"rel(sp,R) \({_sci(rel)}\)"
        if note == "STATA_NOTE":
            stata_path = ORIG_RESULTS / f"{module}_Stata.json"
            st = json.loads(stata_path.read_text(encoding="utf-8"))["rows"][0]
            st_est = float(st["estimate"])
            note_txt = (
                rel_txt
                + rf"; Stata \code{{synth}} ${val_fmt % st_est}$ on the same bytes"
            )
        elif note:
            note_txt = rel_txt + "; " + note
        else:
            note_txt = rel_txt
        lines.append(
            f"{extract} & {stat_label} & {pub_cell} & "
            f"${val_fmt % sp_est}$ & ${val_fmt % r_est}$ & {note_txt} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed .tex differs from regenerated")
    args = ap.parse_args()

    tex = build_table()
    if args.check:
        current = OUT_TEX.read_text(encoding="utf-8") if OUT_TEX.exists() else ""
        if current != tex:
            print("DRIFT: manuscript/tables/headline_parity.tex is stale; "
                  "run generate_headline_parity_table.py", file=sys.stderr)
            return 1
        print("OK -- headline_parity.tex matches the orig-parity artifacts")
        return 0

    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text(tex, encoding="utf-8")
    print(f"OK -- wrote {OUT_TEX}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
