#!/usr/bin/env python3
"""Render the committed Track-B Monte Carlo JSON artifacts as JSS tables."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


import sys
_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:  # _paths.py sits beside this script; importlib loaders do not add the script dir
    sys.path.insert(0, _SCRIPTS_DIR)

from _paths import PAPER_ROOT as _PAPER_ROOT
from _paths import statspai_root as _statspai_root

ROOT = _statspai_root()  # see _paths.py: worktree-safe
RESULTS = ROOT / "tests" / "coverage_monte_carlo" / "results_b1000"
OUTPUT = _PAPER_ROOT / "manuscript" / "tables" / "track_b_monte_carlo.tex"

COVERAGE_NAMES = {
    "sp.regress (HC1) on RCT": (r"\code{sp.regress} (HC1)", "RCT with covariates"),
    "sp.regress 2x2 DiD": (r"\code{sp.regress} 2x2 DiD", "2-period homogeneous DiD"),
    "sp.ivreg (HC1) on strong-Z IV": (r"\code{sp.ivreg} (HC1)", "strong binary-Z IV"),
    "sp.callaway_santanna simple ATT (staggered)": (
        r"\code{sp.callaway\_santanna}",
        "homogeneous staggered ATT",
    ),
    "sp.sun_abraham overall ATT (staggered)": (
        r"\code{sp.sun\_abraham}",
        "homogeneous staggered ATT",
    ),
    "sp.panel two-way FE": (
        r"\code{sp.panel} two-way FE",
        "known-coefficient FE panel",
    ),
    "sp.rdrobust sharp (robust CI)": (
        r"\code{sp.rdrobust} sharp",
        "known-jump RD, robust CI",
    ),
    "sp.sdid placebo (1 treated)": (
        r"\code{sp.sdid} (placebo SE)",
        "factor-model panel, 1 treated",
    ),
    "sp.ebalance (CIA, ATT)": (r"\code{sp.ebalance}", "CIA, ATT (M-estimation SE)"),
    "sp.causal_question(design='dml') IRM ATE": (
        r"\code{sp.dml} (IRM)",
        r"binary-\(D\) CIA, IRM ATE",
    ),
    "sp.dml(model='plr') theta": (
        r"\code{sp.dml} (PLR)",
        r"continuous-\(D\) PLR, default learners",
    ),
    "sp.causal_question(design='causal_forest') AIPW ATE": (
        r"\code{sp.causal\_forest} (AIPW)",
        r"binary-\(D\) CIA, population ATE",
    ),
}

SIZE_NAMES = {
    "sp.regress (HC1) RCT": r"\code{sp.regress} (HC1)",
    "sp.did 2x2": r"\code{sp.did} 2x2",
    "sp.ivreg strong-Z": r"\code{sp.ivreg} strong-Z",
    "sp.rdrobust sharp": r"\code{sp.rdrobust} sharp",
    "sp.panel two-way FE": r"\code{sp.panel} two-way FE",
    "sp.callaway_santanna staggered": r"\code{sp.callaway\_santanna}",
    "sp.ebalance (M-estimation SE)": r"\code{sp.ebalance}",
}

ROBUST_NAMES = {
    "sp.ivreg (HC1) weak instrument (pi=0.10)": (
        r"\code{sp.ivreg}",
        r"weak instrument, median \(F\approx2.5\)",
        "Expected under-coverage; preflight warns and suggests LIML/AR.",
    ),
    "sp.callaway_santanna heterogeneous timing+magnitude": (
        r"\code{sp.callaway\_santanna}",
        "heterogeneous timing and magnitude",
        "Post-fix influence-function scaling remains near nominal.",
    ),
    "sp.causal_forest AIPW under overlap loss": (
        r"\code{sp.causal\_forest}",
        "severe overlap loss",
        "Under-covers as propensities approach 0 and 1; audit flags overlap before interpretation.",
    ),
}


def _load(name: str) -> list[dict]:
    return json.loads((RESULTS / name).read_text(encoding="utf-8"))


def _vec(values: list[float]) -> str:
    return "[" + ", ".join(f"{x:.3g}" for x in values) + "]"


def _tex_int(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def render() -> str:
    coverage = _load("coverage_b1000.json")
    size_power = _load("size_power_b1000.json")
    if set(SIZE_NAMES) != {row["name"] for row in size_power}:
        raise ValueError("size/power artifact rows drifted from the declared audit set")
    robustness = _load("coverage_robustness_b1000.json")
    lines = [
        "% AUTO-GENERATED by replication/scripts/generate_track_b_tables.py",
        r"\begin{table}[!ht]",
        r"\centering\small",
        r"\begingroup\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{@{}L{0.25\linewidth}L{0.21\linewidth}rrrrrr@{}}",
        r"\toprule",
        r"Estimator & DGP & Cover. & Bias & MC SD & Mean SE & SE/SD & CI len. \\",
        r"\midrule",
    ]
    for row in coverage:
        estimator, dgp = COVERAGE_NAMES[row["name"]]
        lines.append(
            f"{estimator} & {dgp} & {row['rate']:.3f} & {row['bias']:+.4f} & "
            f"{row['mc_sd']:.4f} & {row['mean_se']:.4f} & {row['se_sd_ratio']:.2f} & "
            f"{row['mean_ci_length']:.3f} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\endgroup",
            r"\caption{Track B materialized coverage artifacts, all at \(B=1{,}000\). Next to the coverage rate: the estimator's bias, its Monte Carlo SD, the mean reported SE, their ratio (SE calibration: 1 is exact, above 1 conservative), and the mean interval length. The 99\% Wilson reference band around nominal 0.95 is approximately \([0.935,0.967]\). \code{sp.ivreg} is the same estimator as the \code{sp.iv} alias of Table~\ref{tab:decathlon}. The two DML rows are distinct configurations: the PLR row is the suite member; the IRM row (binary treatment, through \code{sp.causal\_question}) is reported separately and does not stand in for it. The forest row reports the fitted forest's own doubly-robust ATE at the default 2{,}000 trees.}",
            r"\label{tab:track-b-b1000}",
            r"\end{table}",
            "",
            r"\begin{table}[!ht]",
            r"\centering\small",
            r"\begin{tabular}{@{}L{0.25\linewidth}L{0.27\linewidth}rL{0.30\linewidth}@{}}",
            r"\toprule",
            r"Estimator & Stressor & Coverage & Interpretation \\",
            r"\midrule",
        ]
    )
    for row in robustness:
        estimator, stressor, interpretation = ROBUST_NAMES[row["name"]]
        lines.append(
            f"{estimator} & {stressor} (\(B={_tex_int(row['B'])}\)) & "
            f"{row['rate']:.3f} & {interpretation} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\caption{Track B robustness rows. These are descriptive failure-mode checks, not pass/fail calibration claims.}",
            r"\label{tab:track-b-robustness}",
            r"\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"FAIL -- generated Track-B table is stale: {OUTPUT}")
            return 1
        print("OK -- generated Track-B tables match the committed Monte Carlo JSON")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"OK -- wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
