"""Verify active manuscript tables and figures are generated artifacts.

JSS requires every displayed result to be reproducible.  The broad full
audit already re-runs generators; this script records the concrete mapping
from the active LaTeX manuscript inputs to the scripts and source artifacts
that produce them.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import time
from pathlib import Path
from typing import Any

import sys
_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:  # _paths.py sits beside this script; importlib loaders do not add the script dir
    sys.path.insert(0, _SCRIPTS_DIR)

from _paths import PAPER_ROOT as _PAPER_ROOT
from _paths import statspai_root as _statspai_root


HERE = Path(__file__).resolve().parent
PAPER_DIR = _PAPER_ROOT
ROOT = _statspai_root()  # see _paths.py: worktree-safe
MANUSCRIPT_DIR = PAPER_DIR / "manuscript"
RESULTS_DIR = PAPER_DIR / "replication" / "results"
OUT_JSON = RESULTS_DIR / "manuscript_artifact_audit.json"
OUT_MD = RESULTS_DIR / "manuscript_artifact_audit.md"
SOURCE_DATE_EPOCH = os.environ.get("SOURCE_DATE_EPOCH")


def _generated_at_unix() -> int:
    if SOURCE_DATE_EPOCH is not None:
        return int(SOURCE_DATE_EPOCH)
    return int(time.time())

ACTIVE_SECTIONS = {
    "sections/01-introduction-compact.tex",
    "sections/02-architecture-compact.tex",
    "sections/03-agent-facing-compact.tex",
    "sections/04-examples-compact.tex",
    "sections/05-parity-compact.tex",
    "sections/06-performance.tex",
    "sections/07-agent-eval.tex",
    "sections/08-computational-details-compact.tex",
    "sections/09-discussion-compact.tex",
    "sections/appendix.tex",
}

EXPECTED_TABLE_INPUTS = {
    "Paper-JSS/manuscript/generated_claims.tex": {
        "generator": "Paper-JSS/replication/scripts/generate_manuscript_claims.py",
        "sources": [
            "scripts/stability_audit.py",
            "Paper-JSS/replication/scripts/agent_interface_audit.py",
        ],
        "required_snippets": [
            "AUTO-GENERATED by replication/scripts/generate_manuscript_claims.py",
            "\\RegistryTotal",
            "\\SchemaParameterTotal",
        ],
    },
    "Paper-JSS/manuscript/tables/appendix_b_parity.tex": {
        "generator": "Paper-JSS/replication/scripts/gen_appendix_parity.py",
        "sources": [
            "tests/r_parity/results/parity_table_3way.tex",
        ],
        "required_snippets": [
            "AUTO-GENERATED by replication/scripts/gen_appendix_parity.py",
            "\\label{tab:track-a-parity}",
            "\\StatsPAIVersion",
        ],
    },
    "Paper-JSS/manuscript/tables/track_a_cross_language_snapshot.tex": {
        "generator": "tests/r_parity/compare.py",
        "sources": [
            "tests/r_parity/results/parity_table_3way.md",
            "tests/r_parity/results/parity_table_3way.tex",
        ],
        "required_snippets": [
            "AUTO-GENERATED by tests/r_parity/compare.py",
            "T3; seed-replicated",
            "T4; reference disagreement",
        ],
    },
    "Paper-JSS/manuscript/tables/forest_seed_mc.tex": {
        "generator": "Paper-JSS/replication/scripts/generate_forest_seed_table.py",
        "sources": [
            "tests/reference_parity/_fixtures/grf_seed_mc_py.json",
            "tests/reference_parity/_fixtures/grf_seed_mc_R.json",
            "tests/reference_parity/_fixtures/grf_seed_mc_m13_py.json",
            "tests/reference_parity/_fixtures/grf_seed_mc_m13_R.json",
        ],
        "required_snippets": [
            "AUTO-GENERATED by replication/scripts/generate_forest_seed_table.py",
        ],
    },
    "Paper-JSS/manuscript/tables/track_c_perf.tex": {
        "generator": "tests/perf/compare_perf.py",
        "sources": ["tests/perf/results/perf_table.tex"],
        "hash_equal_to": "tests/perf/results/perf_table.tex",
        "required_snippets": [
            "AUTO-GENERATED by tests/perf/compare_perf.py",
            "\\label{tab:track-c-perf}",
        ],
    },
    "Paper-JSS/manuscript/tables/track_b_monte_carlo.tex": {
        "generator": "Paper-JSS/replication/scripts/generate_track_b_tables.py",
        "sources": [
            "tests/coverage_monte_carlo/results_b1000/coverage_b1000.json",
            "tests/coverage_monte_carlo/results_b1000/coverage_robustness_b1000.json",
            "tests/coverage_monte_carlo/results_b1000/size_power_b1000.json",
        ],
        "required_snippets": [
            "AUTO-GENERATED by replication/scripts/generate_track_b_tables.py",
            "\\label{tab:track-b-b1000}",
            "\\label{tab:track-b-robustness}",
        ],
    },
    "Paper-JSS/manuscript/tables/headline_parity.tex": {
        "generator": "Paper-JSS/replication/scripts/generate_headline_parity_table.py",
        "sources": [
            "tests/orig_parity/results/01_card_original_py.json",
            "tests/orig_parity/results/02_mpdta_original_py.json",
            "tests/orig_parity/results/03_basque_original_py.json",
            "tests/orig_parity/results/03_basque_original_Stata.json",
            "tests/orig_parity/results/04b_nsw_psid_original_py.json",
            "tests/orig_parity/results/05_lee_original_py.json",
            "tests/orig_parity/results/06_nhefs_ch12_ipw_py.json",
            "tests/orig_parity/results/07_nhefs_ch13_gformula_py.json",
        ],
        "required_snippets": [
            "AUTO-GENERATED by replication/scripts/generate_headline_parity_table.py",
            "no printed vignette anchor",
            "Stata \\code{synth}",
        ],
    },
    "Paper-JSS/replication/tables/ex07_agent_trace.tex": {
        "generator": "Paper-JSS/replication/scripts/ex07_agent_trace.py",
        "sources": [
            "Paper-JSS/replication/results/ex07_agent_trace.json",
            "Paper-JSS/replication/results/ex07_agent_trace.txt",
        ],
        "required_snippets": [
            "BibTeX entries resolved",
            "Honest-DiD",
            "Recoverable stale-handle error",
        ],
    },
    "Paper-JSS/replication/tables/ex08_three_way.tex": {
        "generator": "Paper-JSS/replication/scripts/ex08_fect_interflex.py",
        "sources": [
            "Paper-JSS/replication/results/ex08_fect_interflex.json",
            "tests/r_parity/results/86_fect_R.json",
            "tests/stata_parity/results/86_fect_Stata.json",
            "tests/r_parity/results/87_interflex_R.json",
            "tests/stata_parity/results/87_interflex_Stata.json",
        ],
        "required_snippets": [
            "fect counterfactual estimators (module 86",
            "interflex marginal effects (module 87",
            "kernel ME at the midpoint, fixed bandwidth (Stata convention)",
        ],
    },
}

EXPECTED_FIGURES = {
    "Paper-JSS/manuscript/figures/ex02_basque_gap.pdf": {
        "generator": "Paper-JSS/replication/scripts/generate_figures.py",
        "sources": [
            "Paper-JSS/replication/scripts/generate_figures.py",
            "Paper-JSS/replication/results/ex02_basque.json",
            "Paper-JSS/replication/tables/ex02_basque.tex",
        ],
    },
    "Paper-JSS/manuscript/figures/ex03_mpdta_event_study.pdf": {
        "generator": "Paper-JSS/replication/scripts/generate_figures.py",
        "sources": [
            "Paper-JSS/replication/scripts/generate_figures.py",
            "Paper-JSS/replication/results/ex03_csdid.json",
            "Paper-JSS/replication/tables/ex03_csdid.tex",
        ],
    },
    "Paper-JSS/manuscript/figures/track_c_loglog.pdf": {
        "generator": "tests/perf/compare_perf.py",
        "sources": [
            "tests/perf/results/perf_table.tex",
            "tests/perf/figures/track_c_loglog.pdf",
        ],
        "hash_equal_to": "tests/perf/figures/track_c_loglog.pdf",
    },
}

EXPECTED_WORKED_EXAMPLE_SCRIPTS = {
    "Paper-JSS/replication/scripts/ex01_card.py",
    "Paper-JSS/replication/scripts/ex02_basque.py",
    "Paper-JSS/replication/scripts/ex03_csdid.py",
    "Paper-JSS/replication/scripts/ex04_lee.py",
    "Paper-JSS/replication/scripts/ex05_lalonde.py",
    "Paper-JSS/replication/scripts/ex06_causal_impact.py",
    "Paper-JSS/replication/scripts/ex08_fect_interflex.py",
}

EXPECTED_WORKED_EXAMPLE_LABELS = {
    "sec:ex-card",
    "sec:ex-basque",
    "sec:ex-csdid",
    "sec:ex-rd",
    "sec:ex-lalonde",
    "sec:ex-causal-impact",
    "sec:ex-fect",
}

EXPECTED_COMPACT_SECTION_COVERAGE = {
    "sections/01-introduction-compact.tex": {
        "role": "contribution framing and validation-tier boundary",
        "anchors": {
            "contribution": "Concretely, the article adds",
            "evidence": "Table~\\ref{tab:scope} makes this boundary explicit",
            "boundary": (
                "not a claim that \\statspai{} supersedes specialized packages"
            ),
        },
    },
    "sections/02-architecture-compact.tex": {
        "role": "software architecture and registry trust tiers",
        "anchors": {
            "contribution": "The architecture has four layers",
            "evidence": (
                "The validation tier is therefore not a paper-only artifact"
            ),
            "integration": "make cross-family handoffs auditable and reproducible",
            "boundary": "Specialized packages remain the reference implementations",
            "backend_boundary": "do not depend on a compiled native extension",
        },
    },
    "sections/03-agent-facing-compact.tex": {
        "role": "agent-facing registry without behavioural overclaim",
        "anchors": {
            "contribution": "typed schemas and an MCP server",
            "evidence": "Every public-facing citation emitted by the package",
            "boundary": "It is not a behavioural claim",
        },
    },
    "sections/04-examples-compact.tex": {
        "role": "worked examples and executable provenance",
        "anchors": {
            "contribution": "seven worked examples as an end-to-end smoke test",
            "evidence": (
                "Table~\\ref{tab:worked-example-map} maps those examples"
            ),
            "boundary": "central boundary: original-data rows are claimed only",
        },
    },
    "sections/05-parity-compact.tex": {
        "role": "validation evidence and hard-case disclosures",
        "anchors": {
            "contribution": "twelve-estimator suite with four evidence tracks",
            "evidence": "(together \\RegistryCertifiedValidated{})",
            "boundary": "only a T2 row is a parity claim",
        },
    },
    "sections/06-performance.tex": {
        "role": "performance evidence and speed-claim limits",
        "anchors": {
            "contribution": "fast enough for routine applied work",
            "evidence": "CPU timings",
            "boundary": "does not support a universal",
        },
    },
    "sections/07-agent-eval.tex": {
        "role": "mechanical and contractual agent-interface evidence",
        "anchors": {
            "contribution": (
                "reports only the \\emph{mechanical} and \\emph{contractual} "
                "evidence"
            ),
            "evidence": "deterministic end-to-end trace",
            "infrastructure": "regenerated from the same validation ledger",
            "boundary": "does not answer whether an LLM agent",
        },
    },
    "sections/08-computational-details-compact.tex": {
        "role": "installation, CI, and reproducibility contract",
        "anchors": {
            "contribution": "rebuild the paper's evidence along three paths",
            "evidence": "runs in under ten minutes",
            "reviewer_commands": "replication/reproduce.py",
            "quick_zip_boundary": "are frozen evidence on that path",
            "boundary": (
                "not require a compiled Rust extension, GPU, or commercial software"
            ),
        },
    },
    "sections/09-discussion-compact.tex": {
        "role": "limitations, unification costs, and maintenance risk",
        "anchors": {
            "contribution": "not a new-estimator paper",
            "evidence": "main limitations are as follows",
            "boundary": "The unification itself has costs",
        },
    },
    "sections/appendix.tex": {
        "role": "the complete Track A ledger, printed rather than archived",
        "anchors": {
            "contribution": "The slice is a reading aid, not the evidence",
            "evidence": "tables/appendix_b_parity.tex",
            "boundary": "Two things this table does not do",
        },
    },
}


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _strip_comments(text: str) -> str:
    lines: list[str] = []
    for line in text.splitlines():
        escaped = False
        kept: list[str] = []
        for char in line:
            if char == "\\":
                escaped = not escaped
                kept.append(char)
                continue
            if char == "%" and not escaped:
                break
            escaped = False
            kept.append(char)
        lines.append("".join(kept))
    return "\n".join(lines)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _resolve_manuscript_path(raw: str) -> Path:
    path = Path(raw)
    if path.suffix == "":
        path = path.with_suffix(".tex")
    return (MANUSCRIPT_DIR / path).resolve()


def _rel(path: Path) -> str:
    return str(path.resolve().relative_to(ROOT))


def _active_section_paths(main_tex: str) -> list[Path]:
    sections = re.findall(r"\\input\{(sections/[^}]+\.tex)\}", main_tex)
    return [(MANUSCRIPT_DIR / section).resolve() for section in sections]


def _external_inputs_and_figures(paths: list[Path]) -> tuple[list[Path], list[Path]]:
    tables: set[Path] = set()
    figures: set[Path] = set()
    for path in paths:
        text = _strip_comments(_read(path))
        for raw in re.findall(r"\\input\{([^}]+)\}", text):
            if raw.startswith("sections/"):
                continue
            tables.add(_resolve_manuscript_path(raw))
        for raw in re.findall(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", text):
            figures.add(_resolve_manuscript_path(raw))
    return sorted(tables), sorted(figures)


def _float_labels(texts: list[str]) -> list[str]:
    labels: set[str] = set()
    for text in texts:
        for label in re.findall(r"\\label\{((?:tab|fig):[^}]+)\}", _strip_comments(text)):
            labels.add(label)
    return sorted(labels)


def _float_references(texts: list[str]) -> list[str]:
    refs: set[str] = set()
    for text in texts:
        text = _strip_comments(text)
        for raw in re.findall(r"\\(?:[Cc]ref|ref)\{([^}]+)\}", text):
            for ref in raw.split(","):
                ref = ref.strip()
                if ref.startswith(("tab:", "fig:")):
                    refs.add(ref)
    return sorted(refs)


def _worked_example_scope(
    main_tex: str,
    examples_text: str,
    failures: list[str],
) -> dict[str, Any]:
    match_text = examples_text.replace(r"\_", "_")
    scripts_present = sorted(
        rel for rel in EXPECTED_WORKED_EXAMPLE_SCRIPTS
        if (ROOT / rel).exists()
    )
    script_mentions = sorted(
        rel for rel in EXPECTED_WORKED_EXAMPLE_SCRIPTS
        if Path(rel).name in match_text
    )
    labels_present = sorted(
        label for label in EXPECTED_WORKED_EXAMPLE_LABELS
        if rf"\label{{{label}}}" in examples_text
    )
    table_script_mentions = sorted(
        set(re.findall(r"ex0[1-8]_[A-Za-z0-9_]+\.py", match_text))
    )
    count_claim_present = (
        "Seven worked examples" in main_tex
        and "seven worked examples" in examples_text
    )
    ok = (
        scripts_present == sorted(EXPECTED_WORKED_EXAMPLE_SCRIPTS)
        and script_mentions == sorted(EXPECTED_WORKED_EXAMPLE_SCRIPTS)
        and labels_present == sorted(EXPECTED_WORKED_EXAMPLE_LABELS)
        and len(table_script_mentions) == 7
        and count_claim_present
    )
    if not ok:
        failures.append(
            "worked-example count/scope drift: "
            f"scripts_present={len(scripts_present)}, "
            f"script_mentions={len(script_mentions)}, "
            f"labels_present={len(labels_present)}, "
            f"table_script_mentions={len(table_script_mentions)}, "
            f"count_claim_present={count_claim_present}"
        )
    return {
        "expected_count": 7,
        "scripts_present": scripts_present,
        "script_mentions": script_mentions,
        "labels_present": labels_present,
        "table_script_mentions": table_script_mentions,
        "count_claim_present": count_claim_present,
        "ok": ok,
    }


def _compact_section_coverage(
    section_paths: list[Path],
    failures: list[str],
) -> dict[str, Any]:
    observed = {
        _rel(path).removeprefix("Paper-JSS/manuscript/"): path
        for path in section_paths
    }
    rows: list[dict[str, Any]] = []
    for section, spec in EXPECTED_COMPACT_SECTION_COVERAGE.items():
        path = observed.get(section)
        if path is None:
            failures.append(f"compact narrative section missing: {section}")
            rows.append(
                {
                    "section": section,
                    "role": spec["role"],
                    "ok": False,
                    "missing_anchors": sorted(spec["anchors"]),
                }
            )
            continue
        text = re.sub(r"\s+", " ", _strip_comments(_read(path)))
        missing = [
            name for name, snippet in spec["anchors"].items()
            if snippet not in text
        ]
        if missing:
            failures.append(
                f"compact narrative anchors missing in {section}: "
                + ", ".join(missing)
            )
        rows.append(
            {
                "section": section,
                "role": spec["role"],
                "ok": not missing,
                "anchors": spec["anchors"],
                "missing_anchors": missing,
            }
        )
    return {
        "expected_sections": sorted(EXPECTED_COMPACT_SECTION_COVERAGE),
        "sections_checked": len(rows),
        "sections_passed": sum(1 for row in rows if row.get("ok")),
        "missing_anchor_count": sum(
            len(row.get("missing_anchors", [])) for row in rows
        ),
        "ok": all(row.get("ok") for row in rows)
        and set(observed) == set(EXPECTED_COMPACT_SECTION_COVERAGE),
        "rows": rows,
    }


def _check_artifact(
    rel: str,
    spec: dict[str, Any],
    failures: list[str],
) -> dict[str, Any]:
    path = ROOT / rel
    exists = path.exists()
    row: dict[str, Any] = {
        "path": rel,
        "exists": exists,
        "generator": spec["generator"],
        "sources": spec.get("sources", []),
    }
    if not exists:
        failures.append(f"missing active manuscript artifact: {rel}")
        return row
    missing_sources = [
        source for source in spec.get("sources", [])
        if not (ROOT / source).exists()
    ]
    if missing_sources:
        failures.append(f"{rel} has missing source artifacts: {missing_sources}")
    row["missing_sources"] = missing_sources

    if path.suffix in {".tex", ".md", ".txt"}:
        text = _read(path)
        missing_snippets = [
            snippet for snippet in spec.get("required_snippets", [])
            if snippet not in text
        ]
        if missing_snippets:
            failures.append(f"{rel} lacks snippets: {missing_snippets}")
        row["missing_snippets"] = missing_snippets

    if "hash_equal_to" in spec:
        other = ROOT / spec["hash_equal_to"]
        if other.exists():
            own_hash = _sha256(path)
            other_hash = _sha256(other)
            row["sha256"] = own_hash
            row["hash_equal_to"] = spec["hash_equal_to"]
            row["hash_equal"] = own_hash == other_hash
            if own_hash != other_hash:
                failures.append(
                    f"{rel} is not byte-identical to {spec['hash_equal_to']}"
                )
        else:
            row["hash_equal"] = False
            failures.append(f"{rel} hash source missing: {spec['hash_equal_to']}")
    return row


def main() -> int:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    failures: list[str] = []

    main_tex_path = MANUSCRIPT_DIR / "main.tex"
    main_tex = _strip_comments(_read(main_tex_path))
    section_paths = _active_section_paths(main_tex)
    section_rels = {_rel(path).removeprefix("Paper-JSS/manuscript/") for path in section_paths}
    if section_rels != ACTIVE_SECTIONS:
        failures.append(
            "active sections differ from audit allow-list: "
            f"found={sorted(section_rels)}"
        )
    missing_sections = [path for path in section_paths if not path.exists()]
    if missing_sections:
        failures.append(
            "missing active manuscript sections: "
            + ", ".join(_rel(path) for path in missing_sections)
        )

    active_paths = [main_tex_path, *section_paths]
    tables, figures = _external_inputs_and_figures(active_paths)
    table_rels = [_rel(path) for path in tables]
    figure_rels = [_rel(path) for path in figures]

    expected_tables = set(EXPECTED_TABLE_INPUTS)
    expected_figures = set(EXPECTED_FIGURES)
    if set(table_rels) != expected_tables:
        failures.append(
            "active table inputs do not match expected generated artifacts: "
            f"found={table_rels}, expected={sorted(expected_tables)}"
        )
    if set(figure_rels) != expected_figures:
        failures.append(
            "active figures do not match expected generated artifacts: "
            f"found={figure_rels}, expected={sorted(expected_figures)}"
        )

    table_rows = [
        _check_artifact(rel, EXPECTED_TABLE_INPUTS[rel], failures)
        for rel in sorted(expected_tables)
    ]
    figure_rows = [
        _check_artifact(rel, EXPECTED_FIGURES[rel], failures)
        for rel in sorted(expected_figures)
    ]
    active_texts = [_read(path) for path in active_paths]
    external_table_texts = [_read(path) for path in tables if path.exists()]
    active_float_labels = _float_labels([*active_texts, *external_table_texts])
    narrative_float_refs = _float_references(active_texts)
    missing_narrative_refs = sorted(
        set(active_float_labels) - set(narrative_float_refs)
    )
    dangling_float_refs = sorted(
        set(narrative_float_refs) - set(active_float_labels)
    )
    if missing_narrative_refs:
        failures.append(
            "active table/figure labels lack narrative references: "
            + ", ".join(missing_narrative_refs)
        )
    if dangling_float_refs:
        failures.append(
            "narrative references point to inactive or missing table/figure labels: "
            + ", ".join(dangling_float_refs)
        )
    examples_path = MANUSCRIPT_DIR / "sections" / "04-examples-compact.tex"
    examples_text = _strip_comments(_read(examples_path))
    worked_examples = _worked_example_scope(main_tex, examples_text, failures)
    compact_section_coverage = _compact_section_coverage(section_paths, failures)
    hash_mismatches = sum(
        1 for row in [*table_rows, *figure_rows]
        if row.get("hash_equal") is False
    )

    status = "PASS" if not failures else "FAIL"
    result = {
        "generated_at_unix": _generated_at_unix(),
        "status": status,
        "active_sections": sorted(section_rels),
        "table_inputs": table_rels,
        "figures": figure_rels,
        "artifact_count": len(table_rows) + len(figure_rows),
        "hash_mismatches": hash_mismatches,
        "active_float_labels": active_float_labels,
        "narrative_float_refs": narrative_float_refs,
        "missing_narrative_refs": missing_narrative_refs,
        "dangling_float_refs": dangling_float_refs,
        "worked_examples": worked_examples,
        "compact_section_coverage": compact_section_coverage,
        "tables": table_rows,
        "figure_artifacts": figure_rows,
        "failures": failures,
    }
    OUT_JSON.write_text(json.dumps(result, indent=2, sort_keys=True), encoding="utf-8")

    lines = [
        "# Manuscript Artifact Audit",
        "",
        f"Status: {status}",
        "",
        "Scope: active `main.tex` section inputs, table inputs, and figures",
        "used by the active submission PDF. Inactive long-form section drafts",
        "are intentionally excluded from this audit.",
        "",
        f"Active sections: {len(section_rels)}",
        f"Table inputs: {len(table_rels)}",
        f"Figures: {len(figure_rels)}",
        f"Generated artifacts checked: {len(table_rows) + len(figure_rows)}",
        f"Hash mismatches: {hash_mismatches}",
        f"Active table/figure labels: {len(active_float_labels)}",
        f"Narrative table/figure references: {len(narrative_float_refs)}",
        f"Missing narrative references: {len(missing_narrative_refs)}",
        f"Dangling narrative references: {len(dangling_float_refs)}",
        "Worked-example scripts present: "
        f"{len(worked_examples['scripts_present'])}/"
        f"{worked_examples['expected_count']}",
        "Worked-example script mentions: "
        f"{len(worked_examples['script_mentions'])}/"
        f"{worked_examples['expected_count']}",
        "Worked-example subsection labels: "
        f"{len(worked_examples['labels_present'])}/"
        f"{worked_examples['expected_count']}",
        "Worked-example count claim present: "
        f"{worked_examples['count_claim_present']}",
        "Compact section coverage: "
        f"{compact_section_coverage['sections_passed']}/"
        f"{compact_section_coverage['sections_checked']}",
        "Compact section missing anchors: "
        f"{compact_section_coverage['missing_anchor_count']}",
        "",
        "Artifacts:",
    ]
    for row in [*table_rows, *figure_rows]:
        marker = "PASS" if (
            row.get("exists")
            and not row.get("missing_sources")
            and not row.get("missing_snippets")
            and row.get("hash_equal", True) is not False
        ) else "FAIL"
        lines.append(
            f"- {marker} -- `{row['path']}` generated by `{row['generator']}`"
        )
    lines.extend(["", "Narrative coverage:"])
    if active_float_labels:
        for label in active_float_labels:
            marker = "PASS" if label in narrative_float_refs else "FAIL"
            lines.append(f"- {marker} -- `{label}`")
    else:
        lines.append("- FAIL -- no active table/figure labels detected")
        failures.append("no active table/figure labels detected")
    lines.extend(["", "Compact narrative coverage:"])
    for row in compact_section_coverage["rows"]:
        marker = "PASS" if row.get("ok") else "FAIL"
        missing = ", ".join(row.get("missing_anchors", [])) or "none"
        lines.append(
            f"- {marker} -- `{row['section']}` ({row['role']}); "
            f"missing anchors: {missing}"
        )
    lines.append("")
    if failures:
        lines.append("Failures:")
        lines.extend(f"- {failure}" for failure in failures)
    else:
        lines.append("Failures: none")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"OK -- wrote {OUT_JSON}")
    print(f"OK -- wrote {OUT_MD}")
    return 0 if not failures else 1


if __name__ == "__main__":
    raise SystemExit(main())
