"""sp.cs_jackknife against the authors' reference implementations.

Fixture: ``tests/fixtures/cs_jackknife/castle.csv`` is the locked castle-doctrine
panel of Cheng & Hoekstra (2013) as redistributed (MIT) in Cunningham's mixtape
repository (50 states, 2000-2010; SHA-256 recorded in the JSON). The reference
JSON holds R ``didjack`` 0.1.0 (commit 818c72b7) on R ``did`` 2.3.0 for all
sixteen aggregates, and Stata ``csdidjack`` 0.5.2 (commit 9906b28e) on
``csdid`` 1.81 for the twelve it implements (no event-time aggregation), both
generated by the Paper-DiD-JAE replication scripts ``jackknife_R.R`` /
``jackknife_Stata.do``. Every aggregate, standard error and delete-one
replicate is compared.

Tolerances: R is compared at 1e-10 relative -- both sides solve the same
least-squares problems in double precision and agree to ~4e-15 in practice, so
the budget is loose only against BLAS differences across CI machines. Stata's
tolerance is set in ``STATA_RTOL`` with its reason.
"""

from __future__ import annotations

import hashlib
import json
import warnings
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import statspai as sp

FIX = Path(__file__).parent / "fixtures" / "cs_jackknife"
R_RTOL = 1e-10
# Stata reads the CSV with ``import delimited ..., asdouble``; with that, every
# aggregate, SE and replicate agrees to ~4e-15, so Stata shares R's budget.
# (Stata's default float storage truncates the outcome and weights and opens a
# 2e-7 gap -- the reason the generating do-file reads the CSV asdouble.)
STATA_RTOL = 1e-10

REF = json.loads((FIX / "castle_reference.json").read_text(encoding="utf-8"))


def test_fixture_is_the_locked_panel():
    digest = hashlib.sha256((FIX / "castle.csv").read_bytes()).hexdigest()
    assert digest == REF["data_sha256"]


@lru_cache(maxsize=None)
def _fit(spec: str, agg: str):
    df = pd.read_csv(FIX / "castle.csv")
    cg = "nevertreated" if spec.startswith("never") else "notyettreated"
    w = "popwt" if spec.endswith("_wt") else None
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return sp.cs_jackknife(
            df,
            y="l_homicide",
            g="gvar",
            t="year",
            i="sid",
            type=agg,
            estimator="reg",
            control_group=cg,
            base_period="universal",
            weights=w,
        )


def _rel(a, b):
    return abs(a - b) / abs(b)


@pytest.mark.parametrize(
    "row", REF["R"]["rows"], ids=lambda r: f"R-{r['spec']}-{r['type']}"
)
def test_matches_r_didjack(row):
    jk = _fit(row["spec"], row["type"])
    assert _rel(jk.estimate, row["att"]) < R_RTOL
    assert _rel(jk.se, row["se"]) < R_RTOL
    assert jk.model_info["df"] == row["df"]
    np.testing.assert_allclose(
        jk.detail["att"].to_numpy(), np.asarray(row["atts"]), rtol=R_RTOL, atol=0
    )


@pytest.mark.parametrize(
    "row", REF["Stata"]["rows"], ids=lambda r: f"Stata-{r['spec']}-{r['type']}"
)
def test_matches_stata_csdidjack(row):
    jk = _fit(row["spec"], row["type"])
    assert _rel(jk.estimate, row["att"]) < STATA_RTOL
    assert _rel(jk.se, row["se"]) < STATA_RTOL
    assert jk.model_info["df"] == row["df"]
    np.testing.assert_allclose(
        jk.detail["att"].to_numpy(), np.asarray(row["atts"]), rtol=STATA_RTOL, atol=0
    )
