"""Contracts for active-manuscript artifact provenance."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
AUDIT = (
    REPO_ROOT / "Paper-JSS" / "replication" / "scripts" / "manuscript_artifact_audit.py"
)
RESULTS = REPO_ROOT / "Paper-JSS" / "replication" / "results"

# ``Paper-JSS/`` is a git-ignored, local-only submission working directory
# (see ``.gitignore``); it is absent from fresh clones and CI checkouts. The
# JSS source-snapshot audits only make sense against that local tree, so skip
# the whole module when it is absent rather than erroring on missing scripts.
pytestmark = pytest.mark.skipif(
    not (REPO_ROOT / "Paper-JSS").exists(),
    reason="Paper-JSS/ submission working dir is git-ignored / local-only",
)


def test_active_manuscript_artifacts_have_generators_and_hash_guards() -> None:
    env = os.environ.copy()
    env.setdefault("SOURCE_DATE_EPOCH", "1780185600")
    res = subprocess.run(
        [sys.executable, str(AUDIT)],
        cwd=REPO_ROOT,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    assert res.returncode == 0, res.stderr

    payload = json.loads((RESULTS / "manuscript_artifact_audit.json").read_text())
    artifacts = {
        row["path"]: row for row in [*payload["tables"], *payload["figure_artifacts"]]
    }

    assert payload["status"] == "PASS"
    # Nine body sections plus the appendix carrying the full Track A
    # ledger (Table 16), which is \input from main.tex like any other
    # section and must therefore be covered by the same hash guards.
    expected_sections = [
        "sections/01-introduction-compact.tex",
        "sections/02-architecture-compact.tex",
        "sections/03-agent-facing-compact.tex",
        "sections/04-examples-compact.tex",
        "sections/05-parity-compact.tex",
        "sections/06-performance.tex",
        "sections/07-agent-eval.tex",
        "sections/08-computational-details-compact.tex",
        "sections/09-discussion-compact.tex",
        "sections/appendix.tex",
    ]
    assert payload["active_sections"] == expected_sections
    assert payload["artifact_count"] == 12
    assert payload["hash_mismatches"] == 0
    compact_coverage = payload["compact_section_coverage"]
    assert compact_coverage["ok"] is True
    assert compact_coverage["sections_checked"] == len(expected_sections)
    assert compact_coverage["sections_passed"] == len(expected_sections)
    assert compact_coverage["missing_anchor_count"] == 0
    assert [row["section"] for row in compact_coverage["rows"]] == expected_sections
    assert {
        "Paper-JSS/manuscript/generated_claims.tex",
        "Paper-JSS/manuscript/tables/track_a_cross_language_snapshot.tex",
        "Paper-JSS/manuscript/tables/track_b_monte_carlo.tex",
        "Paper-JSS/manuscript/tables/track_c_perf.tex",
        "Paper-JSS/manuscript/tables/headline_parity.tex",
        "Paper-JSS/replication/tables/ex07_agent_trace.tex",
        "Paper-JSS/replication/tables/ex08_three_way.tex",
        "Paper-JSS/manuscript/figures/ex02_basque_gap.pdf",
        "Paper-JSS/manuscript/figures/ex03_mpdta_event_study.pdf",
        "Paper-JSS/manuscript/figures/track_c_loglog.pdf",
        "Paper-JSS/manuscript/tables/appendix_b_parity.tex",
        "Paper-JSS/manuscript/tables/forest_seed_mc.tex",
    } == set(artifacts)
    assert (
        artifacts["Paper-JSS/manuscript/tables/track_c_perf.tex"]["hash_equal"] is True
    )
    assert (
        artifacts["Paper-JSS/manuscript/figures/track_c_loglog.pdf"]["hash_equal"]
        is True
    )

    snapshot = (
        REPO_ROOT
        / "Paper-JSS"
        / "manuscript"
        / "tables"
        / "track_a_cross_language_snapshot.tex"
    ).read_text()
    assert "AUTO-GENERATED by tests/r_parity/compare.py" in snapshot
    assert "T4; reference disagreement" in snapshot
    assert "T3; seed-replicated" in snapshot
