"""Reference parity: ``sp.survreg`` / ``sp.aft`` (Weibull AFT) vs R ``survival``.

R ``survival::survreg`` (Therneau) is the canonical accelerated-failure-time
reference. StatsPAI's Weibull AFT reproduces the log-time coefficients and
log-scale to within iterative-MLE convergence tolerance (the two solvers stop
at slightly different gradient thresholds, so this is graded ``aligned`` —
matched to a named reference within a documented tolerance — not bit-exact).

Frozen reference: ``_fixtures/aft_R.json`` (R 4.5.2 / survival 3.8.3),
generated by ``_generate_aft_R.R``. Regenerate with::

    Rscript tests/reference_parity/_generate_aft_R.R

Tolerance: coefficients & log-scale within 5e-5 absolute (observed ~1e-5).

References
----------
- Therneau, T. (R ``survival`` package). [@therneau2000modeling]
"""

from __future__ import annotations

import json
import pathlib

import pandas as pd
import pytest

import statspai as sp

_FIXTURES = pathlib.Path(__file__).parent / "_fixtures"
_ATOL = 5e-5


@pytest.fixture(scope="module")
def aft_data():
    return pd.read_csv(_FIXTURES / "aft_data.csv")


@pytest.fixture(scope="module")
def r_reference():
    with open(_FIXTURES / "aft_R.json", encoding="utf-8") as fh:
        return json.load(fh)


def test_survreg_weibull_matches_R(aft_data, r_reference):
    res = sp.survreg(data=aft_data, duration="time", event="event", x=["x", "group"])
    p = res.params
    coef = r_reference["coefficients"]
    assert float(p["_cons"]) == pytest.approx(coef["Intercept"], abs=_ATOL)
    assert float(p["x"]) == pytest.approx(coef["x"], abs=_ATOL)
    assert float(p["group"]) == pytest.approx(coef["group"], abs=_ATOL)
    assert float(p["log(sigma)"]) == pytest.approx(r_reference["log_scale"], abs=_ATOL)


def test_aft_formula_matches_R(aft_data, r_reference):
    res = sp.aft("time + event ~ x + group", aft_data, family="weibull")
    p = res.params
    coef = r_reference["coefficients"]
    assert float(p["Intercept"]) == pytest.approx(coef["Intercept"], abs=_ATOL)
    assert float(p["x"]) == pytest.approx(coef["x"], abs=_ATOL)
    assert float(p["group"]) == pytest.approx(coef["group"], abs=_ATOL)
    assert float(p["log(sigma)"]) == pytest.approx(r_reference["log_scale"], abs=_ATOL)
