"""Weighted Callaway-Sant'Anna parity against R ``did`` 2.3.0.

R ``did::att_gt`` has supported ``weightsname=`` for years; StatsPAI's
``callaway_santanna`` did not, and ``sp.did(..., weights=)`` silently
dropped the argument on the staggered paths. Unit weights are part of
the *estimand* — Baker et al. (2026, §3.1) — so a dropped ω answers a
different question, not a slightly less precise version of the same one.

This module pins the weighted path against the reference implementation
on identical bytes.

Reference generated by ``_generate_cs_weighted_R.R``::

    att_gt(yname="y", tname="t", idname="i", gname="g", xformla = ~ x1,
           weightsname = "w", est_method = <dr|reg|ipw>,
           control_group = <nevertreated|notyettreated>,
           bstrap = FALSE, cband = FALSE, base_period = "universal")
    aggte(., type = <simple|dynamic|group>, bstrap = FALSE, cband = FALSE)

R 4.x, ``did`` 2.3.0.

The panel is engineered so ω matters: a quarter of units carry 20x the
weight and a +4 effect, the rest -1. The unweighted ATT is ~ +0.32 and
the ω-weighted ATT is ~ +3.37 — an order of magnitude apart, so a
silently-dropped weight cannot pass by coincidence.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

import statspai as sp

_FIXTURES = Path(__file__).parent / "_fixtures"
_PANEL = _FIXTURES / "cs_weighted_panel.csv"
_REFERENCE = _FIXTURES / "cs_weighted_reference.csv"

# Nuisance estimation runs through a logit (weighted MLE under ω) and a
# WLS outcome model, so agreement is limited by the two solvers'
# convergence tolerances rather than by the estimator algebra. The
# observed worst case across all 36 cells is 1.6e-11.
_RTOL = 1e-8

# Standard errors now match to machine precision for all three covariate
# strategies. Each reached that point differently:
#
#   reg  — always exact; the control-regression delta-method term was
#          already implemented.
#   ipw  — required arm-specific centring plus the propensity-score
#          estimation effect. Was 9-89% off.
#   dr   — required the same centring plus DRDID's three nuisance
#          estimation terms (``inf.treat.2``, ``inf.cont.2``,
#          ``inf.cont.3``). Was up to 0.9% off.
#
# The budget is 1e-8 rather than 0: both sides run an iterative logit and
# a least-squares solve, so agreement is bounded by solver tolerances.
# Observed worst case across all 72 cells is 4.6e-11.
_SE_RTOL = 1e-8


@pytest.fixture(scope="module")
def panel() -> pd.DataFrame:
    return pd.read_csv(_PANEL, encoding="utf-8")


@pytest.fixture(scope="module")
def reference() -> pd.DataFrame:
    return pd.read_csv(_REFERENCE, encoding="utf-8")


def _cases():
    ref = pd.read_csv(_REFERENCE, encoding="utf-8")
    for _, row in ref.iterrows():
        for agg in ("simple", "dynamic", "group"):
            yield pytest.param(
                row["est"],
                row["control_group"],
                bool(row["weighted"]),
                bool(row["covariates"]),
                agg,
                float(row[f"{agg}_att"]),
                float(row[f"{agg}_se"]),
                id=(
                    f"{row['est']}-{row['control_group']}"
                    f"-{'w' if row['weighted'] else 'unw'}"
                    f"-{'x' if row['covariates'] else 'nox'}-{agg}"
                ),
            )


@pytest.mark.parametrize(
    "est,control_group,weighted,covariates,agg,r_att,r_se", list(_cases())
)
def test_weighted_cs_matches_r_did(
    panel, est, control_group, weighted, covariates, agg, r_att, r_se
):
    fit = sp.callaway_santanna(
        panel,
        y="y",
        g="g",
        t="t",
        i="i",
        x=["x1"] if covariates else None,
        weights="w" if weighted else None,
        estimator=est,
        control_group=control_group,
        base_period="universal",
    )
    out = sp.aggte(fit, type=agg, bstrap=False, cband=False)
    assert out.estimate == pytest.approx(r_att, rel=_RTOL)


@pytest.mark.parametrize(
    "est,control_group,weighted,covariates,agg,r_att,r_se", list(_cases())
)
def test_weighted_cs_se_matches_r_did(
    panel, est, control_group, weighted, covariates, agg, r_att, r_se
):
    """The influence functions must carry ω too, not just the point estimate.

    A weighted point estimate paired with an unweighted SE is the more
    insidious bug: the number moves, so the change looks applied, but the
    confidence interval is for a different estimator.
    """
    fit = sp.callaway_santanna(
        panel,
        y="y",
        g="g",
        t="t",
        i="i",
        x=["x1"] if covariates else None,
        weights="w" if weighted else None,
        estimator=est,
        control_group=control_group,
        base_period="universal",
    )
    out = sp.aggte(fit, type=agg, bstrap=False, cband=False)
    assert out.se == pytest.approx(r_se, rel=_SE_RTOL)


def test_weighting_actually_moves_the_estimate(panel, reference):
    """Guard against a future regression that re-drops ω silently.

    If ``weights=`` ever stops being honoured, the weighted and
    unweighted rows collapse onto each other and every parity assertion
    above would still pass for the unweighted half. This asserts the gap.
    """
    unw = reference[~reference["weighted"].astype(bool)]["simple_att"]
    wtd = reference[reference["weighted"].astype(bool)]["simple_att"]
    assert unw.max() < 1.0 < wtd.min(), "fixture no longer separates the two"

    a = sp.callaway_santanna(panel, y="y", g="g", t="t", i="i", x=["x1"])
    b = sp.callaway_santanna(panel, y="y", g="g", t="t", i="i", x=["x1"], weights="w")
    assert abs(b.estimate - a.estimate) > 1.0


def test_dr_nuisance_correction_vanishes_without_covariates():
    """The DR estimation-effect correction is identically zero at X = 1.

    This is the basis of the migration note's claim that no
    covariate-free ``estimator="dr"`` result moved. With an
    intercept-only design the two outcome-regression terms
    (``inf.treat.2`` and ``inf.cont.3``) cancel, and the score term
    vanishes because a constant propensity makes the control-arm
    residual mean exactly zero. Asserted numerically rather than argued,
    so the claim cannot rot.
    """
    import importlib

    import numpy as np

    cs = importlib.import_module("statspai.did.callaway_santanna")
    rng = np.random.default_rng(0)
    for _ in range(4):
        n = 400
        d = (rng.random(n) < 0.4).astype(float)
        w = rng.gamma(2, 1, n) * 5
        w = w / w.mean()  # the invariant _estimate_single_att enforces
        dy = 1.0 + 2.0 * d + rng.normal(0, 1, n)

        pscore = cs._estimate_pscore(d, None, n, w)
        keep = cs._pscore_trim_mask(pscore, d, 0.995)
        m_hat = cs._estimate_outcome_reg(dy, 1 - d, None, n, w)
        resid = dy - m_hat
        p_d = float(np.mean(w * d))
        ipw_raw = keep * w * pscore * (1 - d) / (1 - pscore)
        ipw_denom = float(ipw_raw.mean())
        eta_c = float(np.mean((ipw_raw / ipw_denom) * resid))

        adj = cs._dr_estimation_effect(
            dy=dy,
            d=d,
            x=None,
            w=w,
            keep=keep,
            pscore=pscore,
            resid=resid,
            eta_c=eta_c,
            p_d=p_d,
            ipw_denom=ipw_denom,
        )
        assert adj is not None
        assert np.max(np.abs(adj)) < 1e-12
