"""Stata ``nprobust::lprobust`` parity for ``sp.lprobust_at_point``.

``lprobust`` is the engine ``did_had`` is built on — it computes the
counterfactual outcome evolution of a quasi-untreated group as the local
polynomial intercept at dose zero, and ``did_had`` reads four numbers off
its ``e(Result)``. Reproducing it exactly is a precondition for
reproducing ``did_had`` at all, so it is pinned here on its own, at
**supplied** bandwidths.

Bandwidth *selection* (the MSE-DPI family) is deliberately out of scope:
conflating the estimator with the selector makes any mismatch impossible
to localize. This module fixes ``h`` and ``b`` so a failure can only mean
the estimator moved.

Golden numbers from Stata 18 MP, ``nprobust`` (installed from the
authors' repo), generated by
``tests/stata_parity/option_parity/86_lprobust.do`` over three kernels ×
three bandwidths, plus one case with ``b != h`` — the case that catches
whether the fit uses the union of the two bandwidth windows.

Tolerance
---------
1e-7 on all four reported quantities; observed worst case 9.2e-9. The
residual is float accumulation, not a convention difference: ``N`` agrees
exactly in every cell, which is the discrete check that both sides
selected the same observations.
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
import pandas as pd
import pytest

import statspai as sp

_HERE = pathlib.Path(__file__).resolve().parents[1] / "stata_parity" / "option_parity"
_DATA = _HERE / "data_86_lprobust.csv"
_GOLDEN = _HERE / "results" / "86_lprobust_Stata.json"

ATOL = 1e-7


@pytest.fixture(scope="module")
def xy():
    d = pd.read_csv(_DATA)
    return d["d"].to_numpy(float), d["y"].to_numpy(float)


@pytest.fixture(scope="module")
def golden() -> dict:
    return {
        k: v
        for k, v in json.loads(_GOLDEN.read_text(encoding="utf-8")).items()
        if not k.startswith("_")
    }


def _case_args(key: str):
    """Decode a fixture key into (kernel, h, b)."""
    if key.startswith("epa_h0.8_b"):
        return "epanechnikov", 0.8, float(key.rsplit("_b", 1)[1])
    kernel, hs = key.rsplit("_h", 1)
    h = float(hs)
    return kernel, h, h


class TestLprobustParity:
    def test_every_fixture_case_matches(self, xy, golden):
        x, y = xy
        worst = 0.0
        for key, want in golden.items():
            kernel, h, b = _case_args(key)
            got = sp.lprobust_at_point(x, y, 0.0, h=h, b=b, kernel=kernel)
            assert got.n_eff == want["N"], (
                f"{key}: effective N {got.n_eff} vs Stata {want['N']} — the "
                "two sides selected different observations"
            )
            for field in ("tau_us", "tau_bc", "se_us", "se_rb"):
                diff = abs(getattr(got, field) - want[field])
                worst = max(worst, diff)
                assert diff < ATOL, (
                    f"{key}.{field}: {getattr(got, field):.15f} vs Stata "
                    f"{want[field]:.15f} (diff {diff:.2e})"
                )
        assert worst < ATOL

    def test_fixture_covers_every_kernel_and_a_distinct_bias_bandwidth(self, golden):
        """Guard the fixture itself, not just the comparison."""
        kernels = {_case_args(k)[0] for k in golden}
        assert kernels == {"epanechnikov", "triangular", "uniform"}
        assert any(b != h for _, h, b in map(_case_args, golden)), (
            "at least one case must have b != h, or the union-window "
            "behaviour is never exercised"
        )

    def test_union_window_is_what_n_reports(self, xy, golden):
        """With b > h the fit spans the LARGER window.

        Reporting the h-window instead gives 241 where Stata gives 317 on
        this fixture. That is not cosmetic: those rows genuinely enter the
        bias-correction step, so a mismatch here means tau_bc is being
        computed on the wrong sample.
        """
        x, y = xy
        got = sp.lprobust_at_point(x, y, 0.0, h=0.8, b=1.2)
        assert got.n_eff == golden["epa_h0.8_b1.2"]["N"] == 317
        narrower = sp.lprobust_at_point(x, y, 0.0, h=0.8, b=0.8)
        assert narrower.n_eff == 241


class TestLprobustProperties:
    """Behaviour that parity alone does not pin."""

    def test_robust_se_exceeds_conventional(self, xy):
        """Bias correction costs variance; that is the whole trade."""
        x, y = xy
        got = sp.lprobust_at_point(x, y, 0.0, h=0.8)
        assert got.se_rb > got.se_us

    def test_bias_is_the_difference_of_the_two_fits(self, xy):
        x, y = xy
        got = sp.lprobust_at_point(x, y, 0.0, h=0.8)
        assert got.bias == pytest.approx(got.tau_us - got.tau_bc, abs=1e-15)

    def test_recovers_a_known_intercept(self):
        """Correctness beyond parity: both packages could be wrong together.

        A large, low-noise sample from a known function must return its
        value at the evaluation point.
        """
        rng = np.random.default_rng(11)
        x = np.abs(rng.gamma(1.4, 0.6, 8000))
        y = 2.5 + 1.3 * x - 0.4 * x**2 + rng.normal(0, 0.05, 8000)
        got = sp.lprobust_at_point(x, y, 0.0, h=0.5)
        assert got.tau_us == pytest.approx(2.5, abs=0.02)
        assert got.tau_bc == pytest.approx(2.5, abs=0.02)

    def test_default_bias_bandwidth_is_h(self, xy):
        x, y = xy
        assert sp.lprobust_at_point(x, y, 0.0, h=0.8).b == 0.8

    @pytest.mark.parametrize(
        "kernel,expected",
        [
            # Epanechnikov 0.75(1-u^2) and triangular (1-|u|) are ZERO at
            # |u| = 1, so the boundary point carries no weight and is not
            # in the window. Uniform is 0.5 there and keeps it. The window
            # is defined by w > 0 (as in lprobust), not by |u| <= 1, and
            # the two differ by exactly this point.
            #
            # Checked against Stata rather than inferred: on
            # x = 0, .25, .5, .5, 1, 1.25, ... with h = 1, lprobust
            # reports N = 4 / 4 / 5 for the three kernels.
            ("epanechnikov", 6),
            ("triangular", 6),
            ("uniform", 7),
        ],
    )
    def test_window_is_defined_by_positive_weight_not_by_distance(
        self, kernel, expected
    ):
        """A leaking boundary would silently widen the effective sample."""
        x = np.array([0.0, 0.2, 0.4, 0.5, 0.7, 0.9, 1.0, 1.5, 2.0, 2.5])
        y = np.arange(10.0)
        got = sp.lprobust_at_point(x, y, 0.0, h=1.0, kernel=kernel, n_neighbors=2)
        assert got.n_eff == expected

    def test_gaussian_kernel_has_no_compact_window(self):
        """Every observation carries weight, so n_eff is the whole sample."""
        x = np.array([0.0, 0.2, 0.4, 0.5, 0.7, 0.9, 1.0, 1.5, 2.0, 2.5])
        y = np.arange(10.0)
        got = sp.lprobust_at_point(x, y, 0.0, h=1.0, kernel="gaussian", n_neighbors=2)
        assert got.n_eff == len(x)


class TestLprobustValidation:
    def test_too_few_points_in_window_raises(self, xy):
        x, y = xy
        with pytest.raises(ValueError, match="fall inside the bandwidth"):
            sp.lprobust_at_point(x, y, 0.0, h=1e-6)

    @pytest.mark.parametrize("bad", [0.0, -1.0, np.nan, np.inf])
    def test_invalid_bandwidth_rejected(self, xy, bad):
        x, y = xy
        with pytest.raises(ValueError, match="positive finite bandwidth"):
            sp.lprobust_at_point(x, y, 0.0, h=bad)

    def test_unknown_kernel_rejected(self, xy):
        x, y = xy
        with pytest.raises(ValueError, match="kernel must be one of"):
            sp.lprobust_at_point(x, y, 0.0, h=0.8, kernel="biweight")

    def test_deriv_above_p_rejected(self, xy):
        x, y = xy
        with pytest.raises(ValueError, match="0 <= deriv <= p"):
            sp.lprobust_at_point(x, y, 0.0, h=0.8, p=1, deriv=2)

    def test_mismatched_lengths_rejected(self):
        with pytest.raises(ValueError, match="same length"):
            sp.lprobust_at_point(np.arange(10.0), np.arange(9.0), 0.0, h=1.0)

    def test_non_finite_rows_are_dropped_not_propagated(self, xy):
        x, y = xy
        xn, yn = x.copy(), y.copy()
        yn[0] = np.nan
        xn[1] = np.nan
        got = sp.lprobust_at_point(xn, yn, 0.0, h=0.8)
        assert np.isfinite(got.tau_us) and np.isfinite(got.se_rb)


class TestBandwidthSelection:
    """``mse-dpi`` direct-plug-in selection.

    Pinned against **R** ``nprobust::lpbwselect`` rather than Stata,
    because Stata's ``lprobust`` overrides the selector's ``b`` with
    ``h/rho`` (``rho`` defaults to 1) and so never reports the ``b`` the
    selector actually chose. R reports both, which is the stricter check
    — and R and Stata agree on ``h`` to 4e-9 anyway.

    The Stata implementation is a compiled Mata routine with no readable
    source; the R package implements the same algorithm in readable R,
    which is what this port was written from.
    """

    # nprobust::lpbwselect(y, x, eval=0, kernel="epa", bwselect="mse-dpi")
    R_H = 0.59287569069430
    R_B = 1.02131749854371
    STATA_H = 0.59287568670540

    def test_h_matches_r(self, xy):
        x, y = xy
        got = sp.lpbwselect_mse_dpi(x, y, 0.0)
        assert got["h"] == pytest.approx(self.R_H, abs=1e-10)

    def test_b_matches_r(self, xy):
        """The selector's own b, which Stata's rho=1 hides."""
        x, y = xy
        got = sp.lpbwselect_mse_dpi(x, y, 0.0)
        assert got["b"] == pytest.approx(self.R_B, abs=1e-10)

    def test_h_matches_stata_too(self, xy):
        x, y = xy
        got = sp.lpbwselect_mse_dpi(x, y, 0.0)
        assert got["h"] == pytest.approx(self.STATA_H, abs=1e-7)

    def test_b_exceeds_h_here(self, xy):
        """Pins that b and h are genuinely different objects.

        did_had uses h for BOTH, inheriting lprobust's rho=1. If a future
        change passed the selector's b as the bias bandwidth, every
        bias-correction window would silently widen.
        """
        x, y = xy
        got = sp.lpbwselect_mse_dpi(x, y, 0.0)
        assert got["b"] > got["h"]

    def test_selected_bandwidth_reproduces_the_default_fit(self, xy):
        """Selecting then fitting must equal fitting at the selected h."""
        x, y = xy
        bw = sp.lpbwselect_mse_dpi(x, y, 0.0)
        fit = sp.lprobust_at_point(x, y, 0.0, h=bw["h"], b=bw["h"])
        assert np.isfinite(fit.tau_us) and fit.se_rb > 0

    def test_even_case_is_rejected_not_approximated(self, xy):
        """(p - deriv) even needs an optimization step that is not ported."""
        x, y = xy
        with pytest.raises(NotImplementedError, match="odd"):
            sp.lpbwselect_mse_dpi(x, y, 0.0, p=2, deriv=0)

    def test_too_few_observations_for_bwcheck_raises(self):
        rng = np.random.default_rng(3)
        x = np.abs(rng.gamma(1.4, 0.6, 10))
        with pytest.raises(ValueError, match="bwcheck"):
            sp.lpbwselect_mse_dpi(x, rng.normal(size=10), 0.0)

    @pytest.mark.parametrize("kernel", ["epanechnikov", "triangular", "uniform"])
    def test_every_kernel_selects_a_usable_bandwidth(self, xy, kernel):
        x, y = xy
        got = sp.lpbwselect_mse_dpi(x, y, 0.0, kernel=kernel)
        assert got["h"] > 0 and np.isfinite(got["h"])
