"""Reference parity: ``sp.survreg`` (parametric AFT) vs R ``survival::survreg``.

The four accelerated-failure-time distributions are pinned to R numbers on a
shared fixed Weibull-AFT design (``survreg_aft_data.csv``):

  * ``weibull`` / ``exponential`` / ``lognormal`` / ``loglogistic``
    -> ``survival::survreg(Surv(time, status) ~ x1 + x2, dist = ...)``.

Both implementations use the AFT (log-time) parameterization, so the
regression coefficients are directly comparable, and sp's ``log(sigma)``
parameter equals R's ``Log(scale) = log(survreg$scale)``.

Tolerances / conventions
------------------------
  * Coefficients (all four dists): 1e-3 relative. sp and survreg maximise the
    identical AFT log-likelihood; observed agreement is ~1e-5.
  * Standard errors of the scale-estimating dists (weibull / lognormal /
    loglogistic): 1e-3 relative — both invert the full coefficient+scale
    information, agreeing to ~1e-5.
  * ``log(sigma)`` vs R ``log(scale)``: 1e-3 relative.
  * Exponential SE is a documented convention gap (~1-2%, not pinned tight):
    the exponential model fixes scale = 1, and R inverts only the coefficient
    block of the information whereas sp inverts the full information and reads
    off the coefficient block, so the coefficient SEs differ by a small,
    coefficient-specific factor even though the point estimates match to
    ~1e-5. Checked at a 3e-2 band as a regression guard, not an equality
    claim (cf. the qreg-SE note in test_count_quantile_parity.py).

The fixture is regenerated by ``_generate_survreg_aft_data.py`` (data) and
``_generate_survreg_aft.R`` (R reference). The committed
``survreg_aft_R.json`` is what this test reads; R is not required to run it.

References
----------
- Therneau, T. M. & Grambsch, P. M. (2000). *Modeling Survival Data:
  Extending the Cox Model*. Springer (the R ``survival`` package
  ``survreg``). doi:10.1007/978-1-4757-3294-8
"""

from __future__ import annotations

import json
import pathlib

import pandas as pd
import pytest

import statspai as sp

_FIXTURE_DIR = pathlib.Path(__file__).parent / "_fixtures"
_DISTS = ("weibull", "exponential", "lognormal", "loglogistic")


@pytest.fixture(scope="module")
def aft_data():
    return pd.read_csv(_FIXTURE_DIR / "survreg_aft_data.csv")


@pytest.fixture(scope="module")
def r_reference():
    with open(_FIXTURE_DIR / "survreg_aft_R.json", encoding="utf-8") as f:
        return json.load(f)


@pytest.mark.parametrize("dist", _DISTS)
def test_survreg_coefficients_match_R(aft_data, r_reference, dist):
    res = sp.survreg("time ~ x1 + x2", data=aft_data, event="status", dist=dist)
    ref = r_reference[dist]["coef"]
    for name, rb in ref.items():
        assert float(res.params[name]) == pytest.approx(rb, rel=1e-3), (dist, name)


@pytest.mark.parametrize("dist", ("weibull", "lognormal", "loglogistic"))
def test_survreg_standard_errors_match_R(aft_data, r_reference, dist):
    # Scale-estimating dists: both invert the full information -> SE ~1e-5.
    res = sp.survreg("time ~ x1 + x2", data=aft_data, event="status", dist=dist)
    ref = r_reference[dist]["se"]
    for name in ("_cons", "x1", "x2"):
        assert float(res.std_errors[name]) == pytest.approx(ref[name], rel=1e-3), (
            dist,
            name,
        )


def test_survreg_exponential_se_convention(aft_data, r_reference):
    # Exponential fixes scale = 1; sp and R differ by a small, coefficient-
    # specific factor in the coefficient SE (full- vs coefficient-block
    # information inversion). Regression guard at 3e-2, not an equality claim.
    res = sp.survreg(
        "time ~ x1 + x2", data=aft_data, event="status", dist="exponential"
    )
    ref = r_reference["exponential"]["se"]
    for name in ("_cons", "x1", "x2"):
        assert float(res.std_errors[name]) == pytest.approx(ref[name], rel=3e-2), name


@pytest.mark.parametrize("dist", ("weibull", "lognormal", "loglogistic"))
def test_survreg_log_scale_matches_R(aft_data, r_reference, dist):
    # sp `log(sigma)` == R `log(survreg$scale)`; exponential fixes scale = 1.
    res = sp.survreg("time ~ x1 + x2", data=aft_data, event="status", dist=dist)
    log_sigma = float(res.params["log(sigma)"])
    assert log_sigma == pytest.approx(r_reference[dist]["log_scale"], rel=1e-3)
