"""Reference parity: ``sp.gmm`` (general moment-condition GMM) against R.

Reference
---------
``_fixtures/general_gmm_R.json``, generated by
``_fixtures/_generate_general_gmm_R.R`` using R's ``gmm`` package
(Chaussé 2010, *JSS* 34(11)) on the linear IV moment condition

    E[z (y − x'b)] = 0,   z = (1, z1, z2, z3),  x = (1, x1)

with 4 moments for 2 parameters, so the model is over-identified and the
J statistic is defined. The sample lives in
``_fixtures/general_gmm_data.csv`` at 17 significant digits.

A note on the reference itself
------------------------------
``gmm::gmm`` drives ``optim()`` at its stock tolerances, which on this
design stop about 1e-4 from the optimum — far enough to swamp any
implementation difference and, initially, to make StatsPAI look wrong by
8e-5. Tightening R's control list moves *R* by 1.2e-4 and brings it onto
StatsPAI's answer. The fixture therefore pins the converged values and
also carries ``closed_form_twostep_centered``: the same two-step estimate
computed in R with plain matrix algebra, no ``gmm::gmm`` involved. StatsPAI
reproduces that closed form to 2e-15, which is the real guarantee here —
agreement with a second implementation *and* with the analytic answer.

Tolerance
---------
``rtol = 1e-6`` against R. The residual disagreement is R's remaining
optimiser slack (probed 5e-9 to 7e-8 across the five specifications), not
a convention difference; the closed-form check below is asserted at 1e-12
because there is nothing to slip between two exact solves.

References
----------
Hansen, L.P. (1982). *Econometrica* 50(4), 1029-1054. [@hansen1982large]
Hansen, L.P., Heaton, J. and Yaron, A. (1996). *JBES* 14(3), 262-280.
[@hansen1996finite]
Newey, W.K. and West, K.D. (1987). *Econometrica* 55(3), 703-708.
[@newey1987simple]
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import statspai as sp

FIXTURES = Path(__file__).parent / "_fixtures"
DATA_CSV = FIXTURES / "general_gmm_data.csv"
R_JSON = FIXTURES / "general_gmm_R.json"

RTOL = 1e-6

pytestmark = pytest.mark.skipif(
    not (DATA_CSV.exists() and R_JSON.exists()),
    reason="general-GMM R fixture not generated",
)


@pytest.fixture(scope="module")
def sample() -> pd.DataFrame:
    return pd.read_csv(DATA_CSV)


@pytest.fixture(scope="module")
def rref() -> dict:
    return json.loads(R_JSON.read_text(encoding="utf-8"))


def _design(d: pd.DataFrame):
    X = np.column_stack([np.ones(len(d)), d["x1"].to_numpy(float)])
    Z = np.column_stack(
        [
            np.ones(len(d)),
            d["z1"].to_numpy(float),
            d["z2"].to_numpy(float),
            d["z3"].to_numpy(float),
        ]
    )
    return X, Z, d["y"].to_numpy(float)


def moment_fn(theta, d):
    X, Z, y = _design(d)
    return (y - X @ theta)[:, None] * Z


def jacobian(theta, d):
    X, Z, _ = _design(d)
    return -(Z.T @ X) / len(d)


def _fit(sample, **kwargs):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return sp.gmm(
            moment_fn,
            np.zeros(2),
            sample,
            param_names=["_cons", "x1"],
            jacobian=jacobian,
            # R's gmm centres the moment covariance by default; StatsPAI
            # exposes the choice and defaults to Stata's uncentred convention,
            # so parity requires asking for R's.
            center=True,
            **kwargs,
        )


def _assert_matches(result, ref: dict, spec: str) -> None:
    for name in ("_cons", "x1"):
        np.testing.assert_allclose(
            float(result.params[name]),
            ref["coef"][name],
            rtol=RTOL,
            err_msg=f"[{spec}] coefficient on {name} differs from R gmm::gmm.",
        )
        np.testing.assert_allclose(
            float(result.std_errors[name]),
            ref["se"][name],
            rtol=RTOL,
            err_msg=f"[{spec}] standard error on {name} differs from R gmm::gmm.",
        )
    np.testing.assert_allclose(
        result.diagnostics["J_stat"],
        ref["J"],
        rtol=RTOL,
        err_msg=f"[{spec}] Hansen J differs from R gmm::gmm.",
    )
    assert result.diagnostics["J_df"] == int(ref["J_df"])


class TestAgainstRgmm:
    def test_twostep_heteroskedasticity_robust(self, sample, rref):
        _assert_matches(_fit(sample, method="twostep"), rref["twostep_mds"], "twostep")

    def test_twostep_iid(self, sample, rref):
        """Same point estimate as MDS — the weight is the same optimal one."""
        _assert_matches(
            _fit(sample, method="twostep", vcov="iid"), rref["twostep_iid"], "iid"
        )

    def test_iterated(self, sample, rref):
        _assert_matches(
            _fit(sample, method="iterative"), rref["iterated_mds"], "iterative"
        )

    def test_cue(self, sample, rref):
        _assert_matches(_fit(sample, method="cue"), rref["cue_mds"], "cue")

    def test_hac_bartlett(self, sample, rref):
        """Exercises the kernel path and its bandwidth convention.

        R's ``sandwich`` evaluates the Bartlett kernel at ``lag / bw``, so the
        weight vanishes at ``lag == bw``. Newey & West state it as
        ``1 − lag/(q+1)`` for truncation lag ``q``; the two agree when
        ``hac_bandwidth = q + 1``. Getting this backwards moved the HAC
        standard errors by 3%, which is exactly the kind of silent convention
        drift this test exists to catch.
        """
        _assert_matches(
            _fit(sample, method="twostep", vcov="hac", hac_bandwidth=2),
            rref["twostep_hac_bartlett2"],
            "hac",
        )

    def test_matches_the_closed_form_exactly(self, sample, rref):
        """The strongest check: an analytic answer, not another optimiser.

        ``sp.gmm`` detects that the moment conditions are affine in θ and
        solves in closed form instead of running BFGS, so this should agree
        to machine precision with the same algebra done independently in R.
        """
        ref = rref["closed_form_twostep_centered"]["coef"]
        result = _fit(sample, method="twostep")
        for name in ("_cons", "x1"):
            np.testing.assert_allclose(
                float(result.params[name]),
                ref[name],
                rtol=1e-12,
                err_msg=(
                    f"[closed form] {name} differs from the analytic two-step "
                    "solution — the affine fast path is wrong, or was skipped."
                ),
            )
        assert result.diagnostics["n_iter"] == 0, (
            "the affine detector did not fire: a linear moment condition was "
            "sent to the optimiser."
        )


class TestAffineDetection:
    """The closed-form path must fire when it is right and not otherwise."""

    def test_nonlinear_moments_still_use_the_optimiser(self, sample):
        """A genuinely nonlinear moment function must not take the fast path.

        ``E[z (y − exp(x'b))] = 0`` has a θ-dependent Jacobian, so the affine
        detector has to reject it. If it did not, the closed form would
        return a linearisation of the wrong model.
        """

        def nl_moment(theta, d):
            X, Z, y = _design(d)
            return (y - np.exp(np.clip(X @ theta, -20, 20)))[:, None] * Z

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            result = sp.gmm(
                nl_moment,
                np.array([0.1, 0.1]),
                sample,
                param_names=["_cons", "x1"],
                method="twostep",
            )
        assert (
            result.diagnostics["n_iter"] > 0
        ), "a nonlinear moment condition was solved in closed form."

    def test_affine_path_agrees_with_the_optimiser(self, sample):
        """Same answer either way — the fast path is a shortcut, not a change.

        Supplying no analytic Jacobian still routes through the detector (it
        uses the numerical one), so comparing against a deliberately
        nonlinear-looking but equivalent parameterisation is the cleanest
        way to check the two agree.
        """
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            fast = sp.gmm(
                moment_fn,
                np.zeros(2),
                sample,
                param_names=["_cons", "x1"],
                jacobian=jacobian,
                method="twostep",
            )

            def wrapped(theta, d):
                # Algebraically identical, but the tiny nonlinearity in the
                # parameterisation makes the detector decline the fast path.
                return moment_fn(np.array([theta[0], theta[1] ** 1.0000000001]), d)

            slow = sp.gmm(
                wrapped,
                np.array([1.0, 2.0]),
                sample,
                param_names=["_cons", "x1"],
                method="twostep",
            )
        np.testing.assert_allclose(
            slow.params.to_numpy(float),
            fast.params.to_numpy(float),
            rtol=1e-4,
            err_msg="closed-form and optimised GMM disagree on the same model.",
        )


class TestMomentCovarianceConventions:
    """``vcov`` and ``center`` are conventions, so pin what they mean."""

    def test_iid_and_mds_coincide_for_cross_sectional_moments(self, sample, rref):
        """Documented equivalence, asserted rather than left in a comment.

        ``sp.gmm`` estimates ``S`` by the moment outer product under both
        ``vcov='iid'`` and ``vcov='mds'``. That is not a shortcut: for
        moments that are independent across observations the two
        assumptions imply the same ``S``, and they separate only through
        the serial-correlation term that ``vcov='hac'`` adds. R's ``gmm``
        agrees — its ``twostep_iid`` and ``twostep_mds`` fixtures are
        identical to the last digit, which is why the two reference rows
        below are the same numbers.

        Without this test the equivalence lives only in a source comment,
        and a future change that gave ``'iid'`` a genuinely homoskedastic
        ``S`` would silently break parity with R instead of failing here.
        """
        assert rref["twostep_iid"] == rref["twostep_mds"], (
            "the R fixture no longer reports iid and MDS as identical; the "
            "equivalence this test documents has to be re-derived."
        )
        iid = _fit(sample, method="twostep", vcov="iid")
        mds = _fit(sample, method="twostep", vcov="mds")
        np.testing.assert_allclose(
            iid.params.to_numpy(float), mds.params.to_numpy(float), rtol=0, atol=0
        )
        np.testing.assert_allclose(
            iid.std_errors.to_numpy(float),
            mds.std_errors.to_numpy(float),
            rtol=0,
            atol=0,
        )
        assert iid.diagnostics["J_stat"] == mds.diagnostics["J_stat"]

    def test_hac_departs_from_mds_once_a_lag_is_included(self, sample):
        """The serial-correlation term is what makes 'hac' different.

        ``hac_bandwidth=1`` weights no lags, so it must reduce exactly to
        the outer product; a bandwidth above 1 must not.
        """
        mds = _fit(sample, method="twostep", vcov="mds")
        hac1 = _fit(sample, method="twostep", vcov="hac", hac_bandwidth=1)
        hac2 = _fit(sample, method="twostep", vcov="hac", hac_bandwidth=2)
        np.testing.assert_allclose(
            hac1.std_errors.to_numpy(float),
            mds.std_errors.to_numpy(float),
            rtol=1e-12,
            err_msg="bandwidth 1 includes no lags and must equal the MDS form",
        )
        assert not np.allclose(
            hac2.std_errors.to_numpy(float), mds.std_errors.to_numpy(float)
        ), "bandwidth 2 weights one lag and must differ from the MDS form"

    def test_centring_changes_the_answer_and_is_not_a_no_op(self, sample):
        """``center`` selects R's convention over Stata's; it must bite.

        If centring ever became a no-op the module would silently report
        Stata's ``S`` while claiming R's, which is precisely the class of
        convention drift the parity harness exists to catch.
        """
        centred = _fit(sample, method="twostep")  # _fit passes center=True
        uncentred = sp.gmm(
            moment_fn,
            np.zeros(2),
            sample,
            param_names=["_cons", "x1"],
            jacobian=jacobian,
            center=False,
            method="twostep",
        )
        assert not np.allclose(
            centred.std_errors.to_numpy(float),
            uncentred.std_errors.to_numpy(float),
            rtol=1e-9,
        ), "centring the moment covariance had no effect on the standard errors"


class TestVarianceSemantics:
    """``se='unadjusted'`` is only the estimator's variance when W is efficient."""

    def test_efficient_weight_makes_both_standard_errors_agree(self, sample):
        """At W = S^-1 the sandwich collapses to (D'S^-1 D)^-1 — assert it."""
        robust = _fit(sample, method="twostep", se="robust")
        efficient = _fit(sample, method="twostep", se="unadjusted")
        np.testing.assert_allclose(
            efficient.std_errors.to_numpy(float),
            robust.std_errors.to_numpy(float),
            rtol=1e-6,
            err_msg=(
                "at the efficient weight the sandwich and the efficient-GMM "
                "variance must coincide; they did not."
            ),
        )

    def test_inefficient_weight_warns_for_unadjusted(self, sample):
        """The old code returned (D'WD)^-1/n here — silently wrong.

        With a deliberately non-efficient weight the efficient-GMM formula
        does not describe the estimator that was computed, so asking for it
        must say so.
        """
        odd_W = np.diag([1.0, 5.0, 0.2, 3.0])
        with pytest.warns(UserWarning, match="not efficient"):
            with warnings.catch_warnings():
                warnings.simplefilter("always")
                sp.gmm(
                    moment_fn,
                    np.zeros(2),
                    sample,
                    W=odd_W,
                    method="onestep",
                    se="unadjusted",
                    jacobian=jacobian,
                    param_names=["_cons", "x1"],
                )

    def test_robust_standard_errors_need_no_warning(self, sample):
        odd_W = np.diag([1.0, 5.0, 0.2, 3.0])
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            sp.gmm(
                moment_fn,
                np.zeros(2),
                sample,
                W=odd_W,
                method="onestep",
                se="robust",
                jacobian=jacobian,
                param_names=["_cons", "x1"],
            )
        assert not any("not efficient" in str(w.message) for w in caught)


class TestClusteredMoments:
    def test_cluster_matches_a_hand_built_sandwich(self, sample):
        """One-way clustering, checked against the definition.

        A one-step fit with an explicit identity weight is used so that the
        weight entering the sandwich is known exactly; the two-step weight is
        itself a function of a first-step estimate, which would make the
        "independent" recomputation depend on reproducing that step too and
        turn this into a re-run of the code under test.
        """
        rng = np.random.default_rng(11)
        groups = rng.integers(0, 25, size=len(sample))
        weight = np.eye(4)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            fit = sp.gmm(
                moment_fn,
                np.zeros(2),
                sample,
                W=weight,
                method="onestep",
                vcov="cluster",
                cluster=groups,
                center=True,
                jacobian=jacobian,
                param_names=["_cons", "x1"],
            )

        theta = fit.params.to_numpy(float)
        G = moment_fn(theta, sample)
        n = len(sample)
        M = G - G.mean(axis=0)
        S = np.zeros((G.shape[1], G.shape[1]))
        for code in np.unique(groups):
            gc = M[groups == code].sum(axis=0)
            S += np.outer(gc, gc)
        S /= n
        D = jacobian(theta, sample)
        DtW = D.T @ weight
        bread = np.linalg.inv(DtW @ D)
        V = bread @ DtW @ S @ DtW.T @ bread / n
        np.testing.assert_allclose(
            fit.std_errors.to_numpy(float),
            np.sqrt(np.diag(V)),
            rtol=1e-10,
            err_msg="clustered GMM standard errors differ from the definition.",
        )

    def test_cluster_requires_the_labels(self, sample):
        with pytest.raises(ValueError, match="requires a `cluster` array"):
            _fit(sample, method="twostep", vcov="cluster")

    def test_cluster_length_is_checked(self, sample):
        with pytest.raises(ValueError, match="entries but the moment function"):
            _fit(sample, method="twostep", vcov="cluster", cluster=np.zeros(5))


class TestConvergenceReporting:
    def test_convergence_is_reported(self, sample):
        fit = _fit(sample, method="cue")
        assert fit.diagnostics["converged"] is True
        assert fit.diagnostics["n_iter"] >= 0

    def test_underidentification_is_rejected(self, sample):
        """Fewer moments than parameters is not a numerical problem to work
        around; it means the model is not identified."""
        with pytest.raises(ValueError, match="under-identified"):
            sp.gmm(
                lambda t, d: moment_fn(t, d)[:, :1],
                np.zeros(2),
                sample,
                param_names=["_cons", "x1"],
            )

    def test_bad_option_values_are_rejected(self, sample):
        for kwargs, match in (
            (dict(method="nonsense"), "method must be"),
            (dict(se="nonsense"), "se must be"),
            (dict(vcov="nonsense"), "vcov must be"),
        ):
            with pytest.raises(ValueError, match=match):
                sp.gmm(moment_fn, np.zeros(2), sample, **kwargs)
