"""``sp.drdid`` reaches all 14 R ``DRDID`` 1.2.3 estimators, exactly.

Context. The question this module answers is "can StatsPAI do everything
``DRDID`` / ``DRDIDpy`` can?". Before 1.23.0 the honest answer was *no*:

* four estimators (``drdid_rc1``, ``drdid_imp_rc1``, ``ipw_did_rc``,
  ``twfe_did_rc``) had no implementation at all;
* two more (``drdid_imp_rc``, ``drdid_imp_rc1``) were unreachable;
* three (``drdid_rc``, ``std_ipw_did_rc``, ``reg_did_rc``) existed only
  as private helpers behind ``callaway_santanna``'s RCS branch;
* and ``sp.drdid`` itself, on repeated cross-sections, computed
  ``drdid_rc1`` under *both* ``method='imp'`` and ``method='trad'`` — the
  argument was silently inert — and reported a nonparametric bootstrap SE
  instead of the Sant'Anna-Zhao influence function.

The parametrisation below is therefore the contract: one row per DRDID
function, each reached through the public ``sp.drdid`` signature.

Why the fixture discriminates. The design has a genuine propensity-score
gradient and an ATT of 1.5, so the fourteen estimators spread from 1.451
(``ipw_did_*``) to 1.697 (``twfe_did_*``), and the SEs from 0.052 to
0.411. Collapsing any two variants onto one engine — the failure mode
that hid here for so long — moves a number by far more than the
tolerance.

Reference generated by ``_generate_drdid_family_R.R`` against R 4.x,
DRDID 1.2.3.

References
----------
Sant'Anna, P.H.C. and Zhao, J. (2020). "Doubly robust
difference-in-differences estimators." *Journal of Econometrics*, 219(1),
101-122. [@santanna2020doubly]
"""

from __future__ import annotations

import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import statspai as sp

_FIXTURES = Path(__file__).parent / "_fixtures"
_LONG = _FIXTURES / "drdid_family_long.csv"
_REFERENCE = _FIXTURES / "drdid_family_reference.csv"

_COVARIATES = ["x1", "x2"]

# Everything is closed-form given the nuisances, so the only slack is the
# logit / WLS solvers. The improved (tilting) variants are looser because
# R solves the tilting problem with a trust-region Newton method and
# StatsPAI with BFGS + Newton refinement; they agree on the ATT to 6e-15
# but the SE inherits ~1e-9 from the propensity score itself.
_RTOL_ATT = 1e-10
_RTOL_SE = 1e-11
_RTOL_SE_TILTED = 1e-7

#: (DRDID function, kwargs to sp.drdid). ``id=`` selects the panel form.
_CASES = [
    ("drdid_panel", dict(id="id", method="trad")),
    ("drdid_imp_panel", dict(id="id", method="imp")),
    ("std_ipw_did_panel", dict(id="id", est_method="ipw")),
    ("ipw_did_panel", dict(id="id", est_method="ipw", normalized=False)),
    ("reg_did_panel", dict(id="id", est_method="reg")),
    ("twfe_did_panel", dict(id="id", est_method="twfe")),
    ("drdid_rc", dict(method="trad")),
    ("drdid_imp_rc", dict(method="imp")),
    ("drdid_rc1", dict(method="trad", locally_efficient=False)),
    ("drdid_imp_rc1", dict(method="imp", locally_efficient=False)),
    ("std_ipw_did_rc", dict(est_method="ipw")),
    ("ipw_did_rc", dict(est_method="ipw", normalized=False)),
    ("reg_did_rc", dict(est_method="reg")),
    ("twfe_did_rc", dict(est_method="twfe")),
]

_TILTED = {"drdid_imp_panel", "drdid_imp_rc", "drdid_imp_rc1"}


@pytest.fixture(scope="module")
def long() -> pd.DataFrame:
    return pd.read_csv(_LONG)


@pytest.fixture(scope="module")
def reference() -> pd.DataFrame:
    return pd.read_csv(_REFERENCE).set_index("fn")


@pytest.mark.parametrize("fn,kwargs", _CASES, ids=[c[0] for c in _CASES])
def test_sp_drdid_matches_the_drdid_function(long, reference, fn, kwargs):
    want = reference.loc[fn]
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        got = sp.drdid(
            long, y="y", group="D", time="post", covariates=_COVARIATES, **kwargs
        )
    assert got.estimate == pytest.approx(want["att"], rel=_RTOL_ATT)
    se_rtol = _RTOL_SE_TILTED if fn in _TILTED else _RTOL_SE
    assert got.se == pytest.approx(want["se"], rel=se_rtol)
    assert got.model_info["engine"] == fn
    assert got.model_info["drdid_reference"] == f"DRDID::{fn}"


def test_every_drdid_estimator_is_covered(reference):
    """The fixture and the case list must not drift apart.

    A new DRDID release adding an estimator should fail here rather than
    quietly leave a hole in the claim this module makes.
    """
    assert set(reference.index) == {fn for fn, _ in _CASES}
    assert len(_CASES) == 14


def test_the_fixture_actually_separates_the_estimators(reference):
    """Guard against a fixture where the variants coincide.

    On a degenerate design several of these estimators collapse onto the
    same number, and a parity suite built on such a fixture proves
    nothing. (That is exactly how ``method=`` being inert on the RCS path
    went unnoticed: on the older fixture ``drdid_rc`` and ``drdid_rc1``
    happened to agree to nine decimals.)
    """
    atts = reference["att"].to_numpy()
    assert atts.max() - atts.min() > 0.2
    # the two DR flavours must differ, or 'imp' vs 'trad' is untested
    assert (
        abs(reference.loc["drdid_rc", "att"] - reference.loc["drdid_imp_rc", "att"])
        > 1e-4
    )
    # rc vs rc1 differ only in efficiency, so compare the SEs
    assert (
        abs(reference.loc["drdid_rc", "se"] - reference.loc["drdid_rc1", "se"]) > 1e-6
    )


def test_method_is_not_inert_on_repeated_cross_sections(long):
    """The regression that motivated this module.

    ``method='imp'`` and ``method='trad'`` used to return the same number
    on the pooled path. They must not.
    """
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        imp = sp.drdid(
            long, y="y", group="D", time="post", covariates=_COVARIATES, method="imp"
        )
        trad = sp.drdid(
            long, y="y", group="D", time="post", covariates=_COVARIATES, method="trad"
        )
    assert abs(imp.estimate - trad.estimate) > 1e-4
    assert imp.model_info["engine"] == "drdid_imp_rc"
    assert trad.model_info["engine"] == "drdid_rc"


def test_standard_errors_are_analytic_not_resampled(long):
    """SEs must be deterministic — the old pooled path bootstrapped them."""
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        a = sp.drdid(
            long,
            y="y",
            group="D",
            time="post",
            covariates=_COVARIATES,
            random_state=1,
        )
        b = sp.drdid(
            long,
            y="y",
            group="D",
            time="post",
            covariates=_COVARIATES,
            random_state=99,
            n_boot=17,
        )
    assert a.se == b.se
    assert a.model_info["se_method"] == "influence_function"


def test_weights_are_honoured(long):
    """`i.weights` must change the answer, and be validated."""
    rng = np.random.default_rng(0)
    df = long.copy()
    df["w"] = rng.uniform(0.5, 2.0, len(df))
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        plain = sp.drdid(df, y="y", group="D", time="post", covariates=_COVARIATES)
        wtd = sp.drdid(
            df, y="y", group="D", time="post", covariates=_COVARIATES, weights="w"
        )
    assert abs(plain.estimate - wtd.estimate) > 1e-6

    df["bad"] = -1.0
    with pytest.raises(Exception, match="non-negative"):
        sp.drdid(
            df, y="y", group="D", time="post", covariates=_COVARIATES, weights="bad"
        )
    with pytest.raises(Exception, match="not in data"):
        sp.drdid(
            df, y="y", group="D", time="post", covariates=_COVARIATES, weights="nope"
        )


def test_inapplicable_flags_warn_rather_than_pass_silently(long):
    """A flag that cannot bite must say so (§7)."""
    with pytest.warns(UserWarning, match="normalized=False only affects"):
        sp.drdid(
            long,
            y="y",
            group="D",
            time="post",
            covariates=_COVARIATES,
            est_method="reg",
            normalized=False,
        )
    with pytest.warns(UserWarning, match="locally_efficient=False only affects"):
        sp.drdid(
            long,
            y="y",
            group="D",
            time="post",
            covariates=_COVARIATES,
            est_method="ipw",
            locally_efficient=False,
        )


def test_bad_est_method_raises(long):
    with pytest.raises(Exception, match="est_method must be"):
        sp.drdid(
            long,
            y="y",
            group="D",
            time="post",
            covariates=_COVARIATES,
            est_method="nonsense",
        )
