"""Reference parity: ``sp.cloglog`` / ``sp.fracreg`` / ``sp.hurdle`` vs R.

Three generalized-linear / count extensions checked against their canonical R
references on a committed deterministic dataset:

  * ``sp.fracreg`` → ``stats::glm(quasibinomial("logit"))`` (fractional
    response) — machine precision (~1e-14), bit-exact.
  * ``sp.hurdle``  → ``pscl::hurdle(dist="poisson", zero.dist="binomial")`` —
    ~2e-8 (within the machine tolerance tier), bit-exact.
  * ``sp.cloglog`` → ``stats::glm(binomial("cloglog"))`` — ~1e-5 (IRLS stops at
    a slightly different gradient threshold), graded aligned.

Frozen reference: ``_fixtures/glm_ext_R.json`` (R 4.5.2 / pscl), generated by
``_generate_glm_ext_R.R``. Regenerate with::

    Rscript tests/reference_parity/_generate_glm_ext_R.R

References
----------
- Papke, L.E. & Wooldridge, J.M. (1996) [fractional response].
- Mullahy, J. (1986) [hurdle models]; Zeileis, Kleiber & Jackman (2008) ``pscl``.
"""

from __future__ import annotations

import json
import pathlib

import pandas as pd
import pytest

import statspai as sp

_FIXTURES = pathlib.Path(__file__).parent / "_fixtures"


@pytest.fixture(scope="module")
def glm_data():
    return pd.read_csv(_FIXTURES / "glm_ext_data.csv")


@pytest.fixture(scope="module")
def r_reference():
    with open(_FIXTURES / "glm_ext_R.json", encoding="utf-8") as fh:
        return json.load(fh)


def test_fracreg_matches_R_quasibinomial(glm_data, r_reference):
    p = sp.fracreg(data=glm_data, y="frac", x=["x1", "x2"]).params
    ref = r_reference["fracreg"]
    assert float(p["_cons"]) == pytest.approx(ref["(Intercept)"], abs=1e-10)
    assert float(p["x1"]) == pytest.approx(ref["x1"], abs=1e-10)
    assert float(p["x2"]) == pytest.approx(ref["x2"], abs=1e-10)


def test_hurdle_matches_pscl(glm_data, r_reference):
    p = sp.hurdle(data=glm_data, y="ycount", x=["x1", "x2"]).params
    count = r_reference["hurdle_count"]
    zero = r_reference["hurdle_zero"]
    assert float(p["count_const"]) == pytest.approx(count["(Intercept)"], abs=1e-6)
    assert float(p["count_x1"]) == pytest.approx(count["x1"], abs=1e-6)
    assert float(p["count_x2"]) == pytest.approx(count["x2"], abs=1e-6)
    assert float(p["hurdle_const"]) == pytest.approx(zero["(Intercept)"], abs=1e-6)
    assert float(p["hurdle_x1"]) == pytest.approx(zero["x1"], abs=1e-6)
    assert float(p["hurdle_x2"]) == pytest.approx(zero["x2"], abs=1e-6)


def test_cloglog_matches_R_glm(glm_data, r_reference):
    p = sp.cloglog(data=glm_data, y="ybin", x=["x1", "x2"]).params
    ref = r_reference["cloglog"]
    assert float(p["Intercept"]) == pytest.approx(ref["(Intercept)"], abs=5e-5)
    assert float(p["x1"]) == pytest.approx(ref["x1"], abs=5e-5)
    assert float(p["x2"]) == pytest.approx(ref["x2"], abs=5e-5)
