"""Reference parity: fuzzy RD against ``rdrobust`` 4.0.0, two-sided design.

Why this file exists separately from ``test_rdrobust_params_parity.py``:
that fixture's ``treat`` is **one-sided** -- nobody below the cutoff is
treated. ``rdbwselect`` detects exactly that case (R's ``perf_comp``: a
side with no first-stage variation), drops ``T``, and returns the *sharp*
bandwidth. A one-sided design therefore cannot tell a correct fuzzy
bandwidth apart from a missing one, which is how ``sp.rdbwselect(fuzzy=)``
went several releases parsing the argument and never passing it on.

Everything here runs on ``rdsenate_fuzzy.csv``, whose ``treat2`` has
noncompliance on both sides, regenerated by
``_fixtures/_generate_rdrobust_fuzzy_R.R``.

Two quantities are pinned that the sharp path cannot reach:

* the bandwidth cascade with the delta-method weights
  ``s = [1/tau_T, -tau_Y/tau_T^2]`` in ``V`` and ``B``;
* the bias-corrected estimate ``tau_bc = tau_cl - s'(bias_Y, bias_T)``,
  which is *not* the ratio of separately bias-corrected numerator and
  denominator, and whose variance carries the covariance between them.
"""

from __future__ import annotations

import json
import pathlib
import warnings

import pandas as pd
import pytest

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    import statspai as sp

_FIX = pathlib.Path(__file__).parent / "_fixtures"
RTOL = 1e-6


@pytest.fixture(scope="module")
def rjson():
    path = _FIX / "rdrobust_fuzzy_R.json"
    if not path.exists():  # pragma: no cover
        pytest.skip("run _generate_rdrobust_fuzzy_R.R first")
    return json.loads(path.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def senate():
    path = _FIX / "rdsenate_fuzzy.csv"
    if not path.exists():  # pragma: no cover
        pytest.skip("run _generate_rdrobust_fuzzy_R.R first")
    return pd.read_csv(path)


def _fit(senate, **kw):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return sp.rdrobust(senate, y="vote", x="margin", c=0, fuzzy="treat2", **kw)


SPECS = [
    ("fuzzy2_p1", dict(p=1)),
    ("fuzzy2_p2", dict(p=2)),
    ("fuzzy2_covs_p1", dict(p=1, covs=["cov1", "cov2"])),
    ("fuzzy2_covs_p2", dict(p=2, covs=["cov1", "cov2"])),
    ("fuzzy2_uniform", dict(kernel="uniform")),
    ("fuzzy2_cerrd", dict(bwselect="cerrd")),
    ("fuzzy2_msetwo", dict(bwselect="msetwo")),
]


@pytest.mark.parametrize("spec,kw", SPECS)
def test_bandwidth_matches_r(rjson, senate, spec, kw):
    ref = rjson[spec]
    res = _fit(senate, **kw)
    info = res.model_info
    h = info["bandwidth_h"]
    b = info["bandwidth_b"]
    h_l, h_r = h if isinstance(h, tuple) else (h, h)
    b_l, b_r = b if isinstance(b, tuple) else (b, b)
    assert h_l == pytest.approx(ref["h_left"], rel=RTOL)
    assert h_r == pytest.approx(ref["h_right"], rel=RTOL)
    assert b_l == pytest.approx(ref["b_left"], rel=RTOL)
    assert b_r == pytest.approx(ref["b_right"], rel=RTOL)


@pytest.mark.parametrize("spec,kw", SPECS)
def test_conventional_estimate_matches_r(rjson, senate, spec, kw):
    ref = rjson[spec]
    res = _fit(senate, **kw)
    assert float(res.detail["estimate"][0]) == pytest.approx(
        ref["coef_conventional"], rel=RTOL
    )


@pytest.mark.parametrize("spec,kw", SPECS)
def test_robust_estimate_matches_r(rjson, senate, spec, kw):
    ref = rjson[spec]
    res = _fit(senate, **kw)
    assert float(res.detail["estimate"][1]) == pytest.approx(
        ref["coef_robust"], rel=RTOL
    )


@pytest.mark.parametrize("spec,kw", SPECS)
def test_standard_errors_match_r(rjson, senate, spec, kw):
    ref = rjson[spec]
    res = _fit(senate, **kw)
    assert float(res.detail["se"][0]) == pytest.approx(ref["se_conventional"], rel=RTOL)
    assert float(res.detail["se"][1]) == pytest.approx(ref["se_robust"], rel=RTOL)


@pytest.mark.parametrize("vce", ["hc0", "hc1", "hc2", "hc3"])
def test_vce_kinds_match_r(rjson, senate, vce):
    ref = rjson[f"fuzzy2_vce_{vce}"]
    res = _fit(senate, vce=vce)
    assert float(res.detail["estimate"][0]) == pytest.approx(
        ref["coef_conventional"], rel=RTOL
    )
    assert float(res.detail["se"][0]) == pytest.approx(ref["se_conventional"], rel=RTOL)
    assert float(res.detail["se"][1]) == pytest.approx(ref["se_robust"], rel=RTOL)


def test_rdbwselect_passes_fuzzy_through(rjson, senate):
    """``sp.rdbwselect(fuzzy=)`` used to parse the argument and discard it.

    The check that matters is not only that the fuzzy bandwidth matches R,
    but that it *differs from the sharp one* -- otherwise this test would
    have passed against the broken version too.
    """
    ref = rjson["fuzzy2_bwselect"]
    got = sp.rdbwselect(senate, y="vote", x="margin", c=0, fuzzy="treat2").iloc[0]
    sharp = sp.rdbwselect(senate, y="vote", x="margin", c=0).iloc[0]
    for key in ("h_left", "h_right", "b_left", "b_right"):
        assert float(got[key]) == pytest.approx(ref[key], rel=RTOL)
    assert abs(float(sharp["h_left"]) - ref["h_left"]) / ref["h_left"] > 0.05


def test_one_sided_noncompliance_falls_back_to_the_sharp_bandwidth(senate):
    """R's ``perf_comp``: no first-stage variation on a side drops ``T``.

    Pinned because it is the reason the defect above stayed hidden, and
    because silently dividing by a zero-variance first stage instead would
    be worse than the fallback.
    """
    one_sided = senate.copy()
    one_sided["treat1"] = (one_sided["margin"] >= 0).astype(float)
    fuzzy_bw = sp.rdbwselect(one_sided, y="vote", x="margin", c=0, fuzzy="treat1")
    sharp_bw = sp.rdbwselect(one_sided, y="vote", x="margin", c=0)
    assert float(fuzzy_bw.iloc[0]["h_left"]) == pytest.approx(
        float(sharp_bw.iloc[0]["h_left"]), rel=1e-12
    )


def test_bias_correction_is_not_a_ratio_of_corrected_parts(rjson, senate):
    """Guard against the pre-1.27.0 construction coming back.

    The retired path divided a sharp bias-corrected estimate by a separately
    bias-corrected first stage. That is a different estimator, and on this
    fixture it lands measurably away from R, so asserting the two are
    distinct keeps the delta-method form from silently regressing.
    """
    ref = rjson["fuzzy2_p1"]
    res = _fit(senate, p=1)
    tau_bc = float(res.detail["estimate"][1])
    assert tau_bc == pytest.approx(ref["coef_robust"], rel=RTOL)

    sharp = sp.rdrobust(senate, y="vote", x="margin", c=0)
    first = sp.rdrobust(senate, y="treat2", x="margin", c=0)
    naive = float(sharp.detail["estimate"][1]) / float(first.detail["estimate"][1])
    assert abs(naive - ref["coef_robust"]) / abs(ref["coef_robust"]) > 1e-3
