"""Reference parity: ``sp.xtlsdvc`` against Stata's ``xtlsdvc`` (Bruno 2005).

Why this file exists
--------------------
``sp.xtlsdvc`` shipped as a registered public function with **10% test
coverage** — no parity test, no property test, nothing exercising the
initialiser or bias-order options. It turns out to be correct (it matches
Stata to 1e-9 across the whole option surface), but nothing was holding it
there.

Reference
---------
``_fixtures/dynpanel_stata.json`` specs ``H1``-``H6``, generated by
``_fixtures/_generate_dynpanel_stata.do`` using ``xtlsdvc`` V1.0.4 (Bruno,
Bocconi) on ``webuse abdata``.

Only **coefficients** are compared. ``xtlsdvc`` reports the *uncorrected*
LSDV standard errors — it documents this, and ``sp.xtlsdvc`` reproduces the
behaviour and warns — so the SEs are not a meaningful parity target
without ``bootstrap()``. That asymmetry is itself asserted below.

Tolerance
---------
``rtol = 1e-7``. The bias expression is evaluated at a consistent initial
estimate obtained by GMM, so the two implementations inherit a shared
dependence on that estimate; probed agreement is 4e-14 to 1.6e-9, the
looser end coming through the Anderson-Hsiao initialiser.

References
----------
Bruno, G.S.F. (2005). Approximating the bias of the LSDV estimator for
dynamic unbalanced panel data models. *Economics Letters* 87(3), 361-366.
[@bruno2005approximating]
Kiviet, J.F. (1995). *Journal of Econometrics* 68(1), 53-78.
[@kiviet1995bias]
Bun, M.J.G. and Kiviet, J.F. (2003). *Economics Letters* 79(2), 145-152.
[@bun2003diminishing]
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import statspai as sp

FIXTURES = Path(__file__).parent / "_fixtures"
DATA_CSV = FIXTURES / "dynpanel_abdata.csv"
STATA_JSON = FIXTURES / "dynpanel_stata.json"

RTOL = 1e-7
_NAME_MAP = {"L1.n": "L.n", "L1.w": "L.w", "L1.k": "L.k"}

pytestmark = pytest.mark.skipif(
    not (DATA_CSV.exists() and STATA_JSON.exists()),
    reason="dynamic-panel Stata fixture not generated",
)


@pytest.fixture(scope="module")
def abdata() -> pd.DataFrame:
    return pd.read_csv(DATA_CSV)


@pytest.fixture(scope="module")
def stata() -> dict:
    return json.loads(STATA_JSON.read_text(encoding="utf-8"))


def _fit(abdata, **kwargs):
    with warnings.catch_warnings():
        # The "SEs are uncorrected unless you bootstrap" advisory is the
        # subject of its own test, not noise to assert around here.
        warnings.simplefilter("ignore")
        return sp.xtlsdvc(abdata, y="n", id="id", time="year", **kwargs)


def _assert_coefficients(result, ref: dict, spec: str) -> None:
    names = list(result.detail["variable"])
    assert len(names) == len(ref["coef"]), (
        f"[{spec}] Stata reports {len(ref['coef'])} coefficients, StatsPAI "
        f"{len(names)}: {names}"
    )
    for i, name in enumerate(names):
        key = _NAME_MAP.get(name, name)
        assert key in ref["coef"], f"[{spec}] unexpected term {name!r}"
        np.testing.assert_allclose(
            float(result.detail["coefficient"].iloc[i]),
            ref["coef"][key],
            rtol=RTOL,
            err_msg=f"[{spec}] coefficient on {name} differs from Stata xtlsdvc.",
        )


class TestAgainstStataXtlsdvc:
    CASES = [
        ("H1_lsdvc_ab_b2", dict(x=["w", "k"], initial="ab", bias_order=2)),
        ("H2_lsdvc_ah_b2", dict(x=["w", "k"], initial="ah", bias_order=2)),
        ("H3_lsdvc_bb_b2", dict(x=["w", "k"], initial="bb", bias_order=2)),
        ("H4_lsdvc_ab_b1", dict(x=["w", "k"], initial="ab", bias_order=1)),
        ("H5_lsdvc_ab_b3", dict(x=["w", "k"], initial="ab", bias_order=3)),
        ("H6_lsdvc_ar1_only", dict(initial="ab", bias_order=2)),
    ]

    @pytest.mark.parametrize("spec,kwargs", CASES, ids=[c[0] for c in CASES])
    def test_coefficients_match(self, abdata, stata, spec, kwargs):
        _assert_coefficients(_fit(abdata, **kwargs), stata[spec], spec)

    def test_every_initialiser_is_actually_used(self, abdata):
        """The three initialisers must give three different answers.

        A correction that ignored its input estimator would still match one
        of the fixtures; requiring all three to differ is what makes the
        parity above informative about ``initial=`` rather than about a
        single hard-coded path.
        """
        rhos = {
            init: float(_fit(abdata, x=["w", "k"], initial=init).estimate)
            for init in ("ab", "ah", "bb")
        }
        assert (
            len({round(v, 8) for v in rhos.values()}) == 3
        ), f"initialisers collapsed to the same estimate: {rhos}"

    def test_bias_order_changes_the_answer(self, abdata):
        """Each expansion order must move the estimate — and less each time.

        Bun & Kiviet (2003) is precisely about diminishing returns: the
        O(1/NT) term should matter less than the O(1/T) one, and the
        O(1/NT^2) term less again. Probed on abdata the increments are
        3.1e-4 then 9.1e-3... the second is *larger*, so only the weaker
        claim — that every order is distinct — is asserted.
        """
        rhos = [
            float(_fit(abdata, x=["w", "k"], bias_order=order).estimate)
            for order in (1, 2, 3)
        ]
        assert (
            len({round(v, 10) for v in rhos}) == 3
        ), f"bias_order did not change the estimate: {rhos}"


class TestBiasCorrectionProperties:
    """What LSDVC is *for*, tested on a DGP with a known answer."""

    @staticmethod
    def _panel(seed=0, N=100, T=6, rho=0.5):
        rng = np.random.default_rng(seed)
        rows = []
        for i in range(N):
            a = rng.normal()
            y = a / (1 - rho) + rng.normal()
            for _ in range(20):
                x = rng.normal()
                y = rho * y + x + a + rng.normal()
            for t in range(T):
                x = rng.normal()
                y = rho * y + x + a + rng.normal()
                rows.append({"id": i, "time": t, "y": y, "x": x})
        return pd.DataFrame(rows)

    @staticmethod
    def _within_rho(df):
        """Hand-rolled LSDV, so the baseline is genuinely independent."""
        d = df.sort_values(["id", "time"]).copy()
        d["ylag"] = d.groupby("id")["y"].shift(1)
        d = d.dropna().copy()
        for c in ("y", "ylag", "x"):
            d[c + "_w"] = d[c] - d.groupby("id")[c].transform("mean")
        X = np.column_stack([d["ylag_w"], d["x_w"]])
        return float(np.linalg.lstsq(X, d["y_w"].to_numpy(), rcond=None)[0][0])

    def test_correction_removes_most_of_the_nickell_bias(self):
        """The point of the estimator, averaged over 8 panels.

        With T=6 the within estimator is biased down by ~0.13 (probed mean
        0.368 against a truth of 0.5). LSDVC should remove most of that.
        Averaging cancels per-draw noise so this probes systematic bias, and
        the assertion is that LSDVC's remaining bias is under a third of
        LSDV's — a wide margin against the probed ~1/10.
        """
        truth = 0.5
        within, corrected = [], []
        for seed in range(8):
            df = self._panel(seed=seed)
            within.append(self._within_rho(df))
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                corrected.append(
                    float(sp.xtlsdvc(df, y="y", x=["x"], id="id", time="time").estimate)
                )
        bias_within = abs(np.mean(within) - truth)
        bias_lsdvc = abs(np.mean(corrected) - truth)
        assert bias_within > 0.05, (
            f"the within estimator is barely biased here ({bias_within:.4f}); "
            "the contrast is vacuous."
        )
        assert bias_lsdvc * 3 < bias_within, (
            f"LSDVC bias {bias_lsdvc:.4f} is not materially below LSDV's "
            f"{bias_within:.4f} — the correction is not working."
        )

    def test_correction_is_upward_for_a_positive_rho(self):
        """Nickell bias is downward for rho > 0, so the fix must add."""
        df = self._panel()
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            corrected = float(
                sp.xtlsdvc(df, y="y", x=["x"], id="id", time="time").estimate
            )
        assert corrected > self._within_rho(df)


class TestStandardErrorsAndOptions:
    def test_analytic_standard_errors_warn_that_they_are_uncorrected(self, abdata):
        """Stata's xtlsdvc reports LSDV SEs; so do we, but loudly.

        Silently returning a standard error that ignores the correction
        would be the worst of both worlds — it looks like inference and is
        not. The warning is the contract.
        """
        with pytest.warns(UserWarning, match="bootstrap"):
            with warnings.catch_warnings():
                warnings.simplefilter("always")
                sp.xtlsdvc(abdata, y="n", x=["w", "k"], id="id", time="year")

    def test_bootstrap_produces_different_and_finite_standard_errors(self, abdata):
        """A small bootstrap must actually replace the analytic SEs."""
        analytic = _fit(abdata, x=["w", "k"])
        booted = _fit(abdata, x=["w", "k"], bootstrap=25, seed=7)
        assert np.isfinite(booted.detail["se"]).all()
        assert (booted.detail["se"] > 0).all()
        assert not np.allclose(
            booted.detail["se"].to_numpy(float),
            analytic.detail["se"].to_numpy(float),
        ), "bootstrap=25 left the analytic standard errors untouched."

    def test_bootstrap_is_reproducible_under_a_seed(self, abdata):
        a = _fit(abdata, x=["w", "k"], bootstrap=15, seed=123)
        b = _fit(abdata, x=["w", "k"], bootstrap=15, seed=123)
        np.testing.assert_array_equal(
            a.detail["se"].to_numpy(float), b.detail["se"].to_numpy(float)
        )

    def test_lag_operator_syntax_is_accepted(self, abdata):
        r = _fit(abdata, x=["l(0/1).w", "k"])
        assert list(r.detail["variable"]) == ["L1.n", "w", "L1.w", "k"]

    @pytest.mark.parametrize(
        "kwargs,match",
        [
            (dict(initial="nonsense"), "initial"),
            (dict(bias_order=0), "bias_order"),
            (dict(bias_order=4), "bias_order"),
        ],
    )
    def test_invalid_options_are_rejected(self, abdata, kwargs, match):
        with pytest.raises(ValueError, match=match):
            _fit(abdata, x=["w", "k"], **kwargs)

    def test_too_few_periods_is_rejected(self, abdata):
        """LSDVC needs a lag and a within transform: T >= 3."""
        short = abdata[abdata["year"] <= abdata["year"].min() + 1]
        with pytest.raises(ValueError, match="3 periods"):
            _fit(short, x=["w", "k"])
