"""Reference parity: ``sp.kaplan_meier`` / ``sp.logrank_test`` vs R ``survival``.

R's ``survival`` package (Therneau) is the canonical reference for the
Kaplan-Meier estimator (``survfit``) and the log-rank test (``survdiff``);
Stata's ``sts`` / ``sts test`` target the same quantities. StatsPAI reproduces
both to machine precision on a committed deterministic two-group dataset.

Frozen reference: ``_fixtures/survival_km_R.json``, generated by
``_generate_survival_km.R`` under R 4.5.2 / survival 3.8.3. Regenerate with::

    Rscript tests/reference_parity/_generate_survival_km.R

Tolerances (observed worst gaps in parentheses):
  * KM S(t) at every event time : 1e-12 absolute (observed ~3e-17)
  * KM median survival          : exact (observed 0)
  * log-rank chi-square         : 1e-10 relative (observed ~8e-16)
  * log-rank p-value            : 1e-10 absolute (observed 0)

References
----------
- Kaplan, E.L. & Meier, P. (1958). Nonparametric Estimation from Incomplete
  Observations. *JASA* 53(282), 457-481.
- Therneau, T. (R ``survival`` package). [@therneau2000modeling]
"""

from __future__ import annotations

import json
import pathlib

import pandas as pd
import pytest

import statspai as sp

_FIXTURES = pathlib.Path(__file__).parent / "_fixtures"


@pytest.fixture(scope="module")
def survival_data():
    return pd.read_csv(_FIXTURES / "survival_km_data.csv")


@pytest.fixture(scope="module")
def r_reference():
    with open(_FIXTURES / "survival_km_R.json", encoding="utf-8") as fh:
        return json.load(fh)


def test_kaplan_meier_survival_curve_matches_R(survival_data, r_reference):
    km = sp.kaplan_meier(survival_data, duration="time", event="event")
    tbl = km.survival_table
    py_surv = dict(zip(tbl["time"].round(6), tbl["survival"]))
    table = r_reference["km_overall"]["table"]
    worst = 0.0
    for t, s_r in zip(table["time"], table["surv"]):
        s_py = py_surv.get(round(float(t), 6))
        assert s_py is not None, f"event time {t} missing from sp.kaplan_meier table"
        worst = max(worst, abs(s_py - s_r))
    assert worst < 1e-12, f"KM S(t) diverged from R survfit: worst |Δ| = {worst:.2e}"


def test_kaplan_meier_median_matches_R(survival_data, r_reference):
    km = sp.kaplan_meier(survival_data, duration="time", event="event")
    assert km.median_survival == pytest.approx(
        r_reference["km_overall"]["median"], abs=1e-12
    )


def test_logrank_statistic_matches_R(survival_data, r_reference):
    lr = sp.logrank_test(survival_data, duration="time", event="event", group="group")
    chisq_r = r_reference["logrank"]["chisq"]
    assert lr["test_statistic"] == pytest.approx(chisq_r, rel=1e-10)
    assert float(lr["p_value"]) == pytest.approx(
        r_reference["logrank"]["pvalue"], abs=1e-10
    )


def test_logrank_observed_expected_match_R(survival_data, r_reference):
    lr = sp.logrank_test(survival_data, duration="time", event="event", group="group")
    obs_r = r_reference["logrank"]["observed"]
    exp_r = r_reference["logrank"]["expected"]
    # Groups are ordered 0, 1 on both sides.
    for i, key in enumerate(["0", "1"]):
        assert lr["observed_events"][key] == pytest.approx(obs_r[i], abs=1e-9)
        assert lr["expected_events"][key] == pytest.approx(exp_r[i], rel=1e-10)
