"""Statistical parity (tier T3): the fect / interflex CV selectors vs R.

``sp.fect(cv=True)`` ports ``fect::fect(CV = TRUE)`` (factor number ``r``
under ``method="ife"``, penalty ``lambda`` under ``method="mc"``) and
``sp.interflex(cv=True)`` ports ``interflex(estimator = "kernel", bw = NULL)``.
Both R routines draw their holdout folds from R's RNG stream, which numpy
cannot reproduce, so a byte-level (T2) comparison is impossible by
construction: two runs of the *R package itself* with different seeds give
different CV curves and can select different tuning values. The evidence
is therefore graded against that across-seed spread, exactly as the forest
estimators are.

Reference: ``_fixtures/fect_interflex_cv_R.json``, generated by
``_generate_fect_interflex_cv_R.R`` (fect 2.4.1, interflex 1.4.0) on the
fixture CSVs written by ``_fixtures/_generate_fect_interflex_cv_data.py``,
with ``set.seed(s)`` for ``s = 1..20`` before each call and every option
at the package default (fect: ``k = 20, cv.prop = 0.1, cv.method =
"rolling", cv.nobs = 3, cv.buffer = 1, criterion = "mspe", cv.rule = "1se"``;
interflex: ``kfold = 10, grid = 30, metric = "MSE"``).

Gates (every number below is derived from the fixture at test time, and
the calibration values are recorded here so a reader can judge them):

* **selection** -- StatsPAI's pick over ``N_PY`` numpy seeds must equal
  R's modal pick, and each single pick must lie inside the set of values
  R's own 20 seeds selected. For the lambda and bandwidth grids R's seeds
  do land on neighbouring grid points (see the calibration table), so a
  one-step difference from the mode is accepted *only* because R exhibits
  it; a pick outside R's observed set fails.
* **curve** -- at every grid point, ``|mean_py - mean_R|`` must be within
  ``4 * sd_R * sqrt(1/N_R + 1/N_PY)``: a four-sigma two-sample z-gate
  built from R's across-seed standard deviation (``N_R = 20``).
* **spread** -- StatsPAI's own across-seed sd of the criterion must be
  within a factor ``SPREAD_BAND`` of R's at the selected grid point, so the
  fold construction produces the same *variability*, not just the same
  mean.
* **deterministic columns** -- the full-data ``sigma2`` / ``IC`` / ``PC``
  columns of fect's ``CV.out.ife`` involve no holdout and must match R to
  ``rel 1e-6`` (same EM map, same start, same ``cv_tol``).
* **refit** -- the CV-selected result equals a direct ``sp.fect(r=...)`` /
  ``sp.fect(lam=...)`` / ``sp.interflex(bw=...)`` call bit for bit.

Calibration (recorded when the fixture was generated; see
``Paper-JSS/notes/2026-09-22-jss-final-drafts/fect_interflex_cv.md`` for the full table):

=====================================  =======================  ======================
quantity                               R (20 seeds)             StatsPAI (5 seeds)
=====================================  =======================  ======================
fect ife: selected r                   2 (20/20)                2 (5/5)
fect ife: MSPE at r = 0..5, mean       5.80 1.42 0.52 1.48      6.22 1.66 0.56 1.56
                                       1.92 2.40                1.90 2.24
fect ife: MSPE across-seed sd          0.76 0.25 0.05 0.23      0.81 0.45 0.03 0.25
                                       0.39 0.58                0.30 0.18
fect ife: sigma2 / IC / PC vs R        --                       rel <= 1e-6 (no holdout)
fect mc: selected lambda_norm          0.0750, index 3 (20/20)  0.0750, index 3 (5/5)
fect mc: rows evaluated (scan stop)    7 of 10                  7 of 10
fect mc: MSPE at index 0..6, mean      5.80 3.97 2.43 1.64      6.22 4.25 2.59 1.73
                                       1.77 2.24 3.71           1.84 2.35 3.94
fect mc: MSPE across-seed sd           0.76 0.57 0.36 0.26      0.81 0.65 0.41 0.25
                                       0.29 0.38 0.58           0.25 0.33 0.58
interflex: selected grid index         15:4 16:4 17:3 18:2      17:3 19:1 21:1
                                       19:4 20:3 (no majority)
interflex: R plateau (mean-min<=sd)    indices 13..24           picks all inside
interflex: MSE at index 16..20, mean   1.1272 1.1260 1.1259     1.1231 1.1229 1.1226
                                       1.1265 1.1277            1.1231 1.1243
interflex: MSE sd at index 16..20      ~0.014                   ~0.015
given-fold fect ife (6 x 20 cells)     --                       max rel 5.9e-8
given-fold fect mc (7 x 20 cells)      --                       max rel 6.5e-9
given-fold interflex (5 x 6 x 10)      --                       max rel 2.8e-13
=====================================  =======================  ======================

The interflex fold draws are heavy-tailed at the smallest bandwidths: on
seed 0 one fold scores MSE 457 at bw = range/100, and R reproduces that
exact number on the same fold (given-fold check), which is why the curve
gate uses both sides' across-seed variances.

Regenerate with::

    python tests/reference_parity/_fixtures/_generate_fect_interflex_cv_data.py
    Rscript tests/reference_parity/_generate_fect_interflex_cv_R.R
"""

from __future__ import annotations

import json
import pathlib
import warnings
from collections import Counter

import numpy as np
import pandas as pd
import pytest

import statspai as sp

_DIR = pathlib.Path(__file__).parent / "_fixtures"
_FECT_CSV = _DIR / "fect_cv_data.csv"
_IFLX_CSV = _DIR / "interflex_cv_data.csv"
_JSON = _DIR / "fect_interflex_cv_R.json"

pytestmark = pytest.mark.skipif(
    not (_FECT_CSV.exists() and _IFLX_CSV.exists() and _JSON.exists()),
    reason="fect / interflex CV fixture is not materialized",
)

N_PY = 5  # numpy seeds per selector
Z_GATE = 4.0  # four-sigma two-sample z-gate on the curve
SPREAD_BAND = 3.0  # sd_py / sd_R within [1/3, 3] at the selected point
REL_DETERMINISTIC = 1e-6


@pytest.fixture(scope="module")
def ref():
    return json.loads(_JSON.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def fect_df():
    return pd.read_csv(_FECT_CSV)


@pytest.fixture(scope="module")
def iflx_df():
    return pd.read_csv(_IFLX_CSV)


def _fect(df, **kw):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        return sp.fect(
            df, y="Y", treat="D", unit="id", time="time", covariates=["X1", "X2"], **kw
        )


@pytest.fixture(scope="module")
def ife_runs(fect_df):
    return [_fect(fect_df, method="ife", cv=True, random_state=s) for s in range(N_PY)]


@pytest.fixture(scope="module")
def mc_runs(fect_df):
    return [_fect(fect_df, method="mc", cv=True, random_state=s) for s in range(N_PY)]


@pytest.fixture(scope="module")
def bw_runs(iflx_df):
    return [
        sp.interflex(
            iflx_df,
            y="Y",
            d="D",
            x="X",
            z=["Z1"],
            estimator="kernel",
            cv=True,
            random_state=s,
        )
        for s in range(N_PY)
    ]


def _curve_gate(py_curves: np.ndarray, r_curves: np.ndarray, label: str):
    """Four-sigma two-sample (Welch) z-gate at every grid point where both
    sides have values (R's MC scan stops early, so some tail points are NaN):
    ``|mean_py - mean_R| <= 4 sqrt(sd_R^2 / n_R + sd_py^2 / n_py)``. Each
    side's own across-seed variance enters because the fold draws are
    heavy-tailed at degenerate settings (a bandwidth of range/100 puts one
    fold in twenty at MSE > 100 on either side), and the given-fold tests
    below pin the scoring itself."""
    mean_r = np.nanmean(r_curves, axis=0)
    sd_r = np.nanstd(r_curves, axis=0, ddof=1)
    n_r_pt = np.sum(np.isfinite(r_curves), axis=0)
    mean_py = np.nanmean(py_curves, axis=0)
    sd_py = np.nanstd(py_curves, axis=0, ddof=1)
    n_py_pt = np.sum(np.isfinite(py_curves), axis=0)
    both = (n_r_pt >= max(3, r_curves.shape[0] // 2)) & (n_py_pt >= 2)
    assert both.sum() >= 3, f"{label}: too few common grid points"
    gate = Z_GATE * np.sqrt(
        sd_r**2 / np.maximum(n_r_pt, 1) + sd_py**2 / np.maximum(n_py_pt, 1)
    )
    diff = np.abs(mean_py - mean_r)
    bad = both & ~(diff <= gate)
    assert not bad.any(), (
        f"{label}: CV curve outside the {Z_GATE}-sigma across-seed gate at grid "
        f"points {np.where(bad)[0].tolist()}: |diff|={diff[bad]} gate={gate[bad]} "
        f"(R mean {mean_r[bad]}, R sd {sd_r[bad]}, py sd {sd_py[bad]})"
    )
    return mean_r, sd_r, mean_py


def _selection_gate(py_picks, r_picks, label: str, adjacency_ok: bool):
    """R's picks are unanimous for r and lambda on this fixture, so the
    modal pick is the gate; a one-step latitude is granted only where R's
    own seeds move across neighbouring grid points."""
    r_counts = Counter(r_picks)
    r_mode = r_counts.most_common(1)[0][0]
    py_mode = Counter(py_picks).most_common(1)[0][0]
    assert (
        py_mode == r_mode
    ), f"{label}: modal selection {py_mode} != R's modal {r_mode} ({r_counts})"
    allowed = set(r_picks)
    if adjacency_ok and len(allowed) > 1:
        allowed |= {r_mode - 1, r_mode + 1}
    for p in py_picks:
        assert (
            p in allowed
        ), f"{label}: selection {p} outside R's observed set {sorted(allowed)}"


def _plateau_gate(py_picks, r_picks, r_curves: np.ndarray, label: str):
    """For a criterion curve that is flat around its minimum (the bandwidth
    MSE here moves by < 1e-3 across six grid points while its across-seed sd
    is ~1.4e-2) R's own 20 seeds spread their pick over that plateau with no
    majority, so a modal gate is not justified. The measured gate is: every
    StatsPAI pick lies in the R plateau -- grid points whose R-mean loss is
    within one R across-seed sd of the R minimum -- and inside R's observed
    selection range widened by one grid step on each side."""
    mean_r = np.nanmean(r_curves, axis=0)
    sd_r = np.nanstd(r_curves, axis=0, ddof=1)
    plateau = set(np.where(mean_r - mean_r.min() <= sd_r)[0].tolist())
    lo, hi = min(r_picks) - 1, max(r_picks) + 1
    for p in py_picks:
        assert p in plateau, f"{label}: pick {p} outside R's plateau {sorted(plateau)}"
        assert (
            lo <= p <= hi
        ), f"{label}: pick {p} outside R's selection range [{lo}, {hi}]"
    assert set(r_picks) <= plateau, f"{label}: R's own picks leave the plateau"


# ----------------------------------------------------------------------
# fect, method = "ife": number of factors
# ----------------------------------------------------------------------


def test_ife_deterministic_columns_match_r(ref, ife_runs):
    """sigma2 / IC / PC are full-data fits (no holdout): same EM map, same
    start, same cv_tol -> rel 1e-6 like the deterministic Track A rows."""
    r0 = next(iter(ref["fect_ife"].values()))
    tab = ife_runs[0].model_info["cv"]["table"]
    assert tab["r"].tolist() == r0["r"]
    for col, key in (("sigma2", "sigma2"), ("IC", "ic"), ("PC", "pc")):
        np.testing.assert_allclose(
            tab[col].to_numpy(), np.asarray(r0[key]), rtol=REL_DETERMINISTIC
        )


def test_ife_selection_matches_r_mode(ref, ife_runs):
    r_picks = [run["r_cv"] for run in ref["fect_ife"].values()]
    py_picks = [run.model_info["r_cv"] for run in ife_runs]
    _selection_gate(py_picks, r_picks, "fect ife r", adjacency_ok=False)


def test_ife_cv_curve_within_r_spread(ref, ife_runs):
    r_curves = np.array([run["mspe"] for run in ref["fect_ife"].values()])
    py_curves = np.array(
        [run.model_info["cv"]["table"]["MSPE"].to_numpy() for run in ife_runs]
    )
    _, sd_r, _ = _curve_gate(py_curves, r_curves, "fect ife MSPE")
    sel = ife_runs[0].model_info["r_cv"]
    sd_py = np.std(py_curves[:, sel], ddof=1)
    assert (
        1 / SPREAD_BAND <= sd_py / sd_r[sel] <= SPREAD_BAND
    ), f"fect ife: across-seed sd at r={sel} py {sd_py:.4f} vs R {sd_r[sel]:.4f}"


def test_ife_refit_equals_direct_call(fect_df, ife_runs):
    run = ife_runs[0]
    direct = _fect(fect_df, method="ife", r=run.model_info["r_cv"])
    assert run.estimate == direct.estimate
    assert (run.detail["att"].to_numpy() == direct.detail["att"].to_numpy()).all()


# ----------------------------------------------------------------------
# fect, method = "mc": nuclear-norm penalty
# ----------------------------------------------------------------------


def test_mc_lambda_grid_matches_r(ref, mc_runs):
    r0 = next(iter(ref["fect_mc"].values()))
    grid = mc_runs[0].model_info["cv"]["grid"]
    np.testing.assert_allclose(grid, r0["lambda_seq"], rtol=REL_DETERMINISTIC)


def test_mc_selection_matches_r_mode(ref, mc_runs):
    r0 = next(iter(ref["fect_mc"].values()))
    seq = np.asarray(r0["lambda_seq"])
    r_picks = [
        int(np.argmin(np.abs(seq - run["lambda_cv"])))
        for run in ref["fect_mc"].values()
    ]
    py_picks = [run.model_info["cv"]["selected_index"] for run in mc_runs]
    _selection_gate(py_picks, r_picks, "fect mc lambda", adjacency_ok=True)


def test_mc_cv_curve_within_r_spread(ref, mc_runs):
    n_grid = len(next(iter(ref["fect_mc"].values()))["lambda_seq"])

    def _pad(v):
        out = np.full(n_grid, np.nan)
        v = np.asarray([np.nan if x is None else x for x in v], dtype=float)
        out[: len(v)] = v
        return out

    r_curves = np.array([_pad(run["mspe"]) for run in ref["fect_mc"].values()])
    py_curves = np.array(
        [_pad(run.model_info["cv"]["table"]["MSPE"].to_numpy()) for run in mc_runs]
    )
    _, sd_r, _ = _curve_gate(py_curves, r_curves, "fect mc MSPE")
    sel = mc_runs[0].model_info["cv"]["selected_index"]
    sd_py = np.nanstd(py_curves[:, sel], ddof=1)
    assert 1 / SPREAD_BAND <= sd_py / sd_r[sel] <= SPREAD_BAND


def test_mc_refit_equals_direct_call(fect_df, mc_runs):
    run = mc_runs[0]
    direct = _fect(fect_df, method="mc", lam=run.model_info["lambda_cv"])
    assert run.estimate == direct.estimate


# ----------------------------------------------------------------------
# interflex, estimator = "kernel": bandwidth
# ----------------------------------------------------------------------


def test_kernel_bw_grid_matches_r(ref, bw_runs):
    r0 = next(iter(ref["interflex_kernel"].values()))
    np.testing.assert_allclose(
        bw_runs[0].model_info["cv"]["grid"], r0["grid"], rtol=REL_DETERMINISTIC
    )
    assert (
        bw_runs[0].model_info["cv"]["table"]["num_eff_points"].tolist()
        == r0["num_eff_points"]
    )


def test_kernel_bw_selection_in_r_plateau(ref, bw_runs):
    r0 = next(iter(ref["interflex_kernel"].values()))
    grid = np.asarray(r0["grid"])
    r_picks = [
        int(np.argmin(np.abs(grid - run["bw"])))
        for run in ref["interflex_kernel"].values()
    ]
    py_picks = [run.model_info["cv"]["selected_index"] for run in bw_runs]
    r_curves = np.array([run["mse"] for run in ref["interflex_kernel"].values()])
    _plateau_gate(py_picks, r_picks, r_curves, "interflex bw")


def test_kernel_cv_curve_within_r_spread(ref, bw_runs):
    r_curves = np.array([run["mse"] for run in ref["interflex_kernel"].values()])
    py_curves = np.array(
        [run.model_info["cv"]["table"]["mse"].to_numpy() for run in bw_runs]
    )
    _, sd_r, _ = _curve_gate(py_curves, r_curves, "interflex kernel MSE")
    sel = bw_runs[0].model_info["cv"]["selected_index"]
    sd_py = np.std(py_curves[:, sel], ddof=1)
    assert 1 / SPREAD_BAND <= sd_py / sd_r[sel] <= SPREAD_BAND


def test_kernel_refit_equals_direct_call(iflx_df, bw_runs):
    run = bw_runs[0]
    direct = sp.interflex(
        iflx_df,
        y="Y",
        d="D",
        x="X",
        z=["Z1"],
        estimator="kernel",
        bw=run.model_info["bw_cv"],
    )
    assert run.estimate == direct.estimate
    assert (run.detail["me"].to_numpy() == direct.detail["me"].to_numpy()).all()


# ----------------------------------------------------------------------
# Given the fold, the scoring is deterministic: T2 on identical folds
# ----------------------------------------------------------------------

_FECT_FOLDS = _DIR / "fect_cv_folds_R.json"
_IFLX_FOLDS = _DIR / "interflex_cv_folds.json"
_IFLX_FOLDS_R = _DIR / "interflex_cv_folds_R.json"
REL_GIVEN_FOLD_IFLX = 1e-9  # measured 2.8e-13 (numpy lstsq vs R glm QR)
REL_GIVEN_FOLD_FECT = (
    1e-6  # measured 5.9e-8: same EM map / start / cv_tol, roundoff x iterations
)


@pytest.mark.skipif(not _FECT_FOLDS.exists(), reason="fect given-fold fixture missing")
@pytest.mark.parametrize("method", ["ife", "mc"])
def test_fect_scoring_matches_r_on_identical_folds(fect_df, method, monkeypatch):
    """Replay the 20 rolling folds fect built (set.seed(1)) and compare the
    fold x grid MSPE matrix and fect's pooled MSPE with R's, cell by cell."""
    from statspai.synth import _fect_cv as cvmod

    ref = json.loads(_FECT_FOLDS.read_text(encoding="utf-8"))
    folds = [
        (np.asarray(f["cv_id"], dtype=int) - 1, np.asarray(f["est_id"], dtype=int) - 1)
        for f in ref["folds"]
    ]
    monkeypatch.setattr(cvmod, "_rolling_folds", lambda *a, **k: folds)
    if method == "ife":
        run = _fect(fect_df, method="ife", cv=True, r_range=(0, 5))
        r_mat = np.asarray(ref["mspe_ife_by_fold"], dtype=float)
        pooled_r = np.asarray(ref["pooled_mspe_ife"], dtype=float)
    else:
        run = _fect(fect_df, method="mc", cv=True, lambda_grid=ref["lambda_grid"])
        r_mat = np.asarray(ref["mspe_mc_by_fold"], dtype=float)
        pooled_r = np.asarray(ref["pooled_mspe_mc"], dtype=float)
    cvi = run.model_info["cv"]
    assert cvi["n_scored_per_fold"] == [len(e) for _, e in folds]
    py_mat = cvi["fold_scores"].iloc[:, 1:].to_numpy(dtype=float)
    n_eval = py_mat.shape[0]  # the MC scan may stop before the end of the grid
    np.testing.assert_allclose(py_mat, r_mat[:n_eval], rtol=REL_GIVEN_FOLD_FECT)
    np.testing.assert_allclose(
        cvi["table"]["MSPE"].to_numpy(dtype=float),
        pooled_r[:n_eval],
        rtol=REL_GIVEN_FOLD_FECT,
    )


@pytest.mark.skipif(
    not (_IFLX_FOLDS.exists() and _IFLX_FOLDS_R.exists()),
    reason="interflex given-fold fixture missing",
)
def test_kernel_scoring_matches_r_on_identical_folds(iflx_df, monkeypatch):
    """Replay StatsPAI's fold assignments through interflex's own
    getError.CV (R) and compare the per-fold MSE / MAE / Num.Eff.Points at
    six bandwidths -- the five smallest (near-singular local fits, MSE up to
    ~460 on one fold) and a plateau point."""
    from statspai.regression import interflex as mod

    spec = json.loads(_IFLX_FOLDS.read_text(encoding="utf-8"))
    ref = json.loads(_IFLX_FOLDS_R.read_text(encoding="utf-8"))
    grid = np.asarray(ref["meta"]["grid"], dtype=float)
    idx = [int(i) for i in spec["grid_indices"]]
    for seed, fold_1based in spec["folds"].items():
        fold = np.asarray(fold_1based, dtype=int) - 1
        monkeypatch.setattr(mod, "_create_folds", lambda labels, k, rng, _f=fold: _f)
        run = sp.interflex(
            iflx_df,
            y="Y",
            d="D",
            x="X",
            z=["Z1"],
            estimator="kernel",
            cv=True,
            bw_grid=[float(grid[i]) for i in idx],
            random_state=0,
        )
        losses = run.model_info["cv"]["fold_losses"].iloc[:, 1:].to_numpy(dtype=float)
        table = run.model_info["cv"]["table"]
        for row, gi in enumerate(idx):
            r_row = ref["seeds"][seed][str(gi)]
            np.testing.assert_allclose(
                losses[row], r_row["mse"], rtol=REL_GIVEN_FOLD_IFLX
            )
            assert table["num_eff_points"].iloc[row] == np.mean(r_row["n_eff"])
            np.testing.assert_allclose(
                table["mae"].iloc[row], np.mean(r_row["mae"]), rtol=REL_GIVEN_FOLD_IFLX
            )
