"""Stata ``did_had`` parity for ``sp.did_had``.

Heterogeneous-adoption DiD (de Chaisemartin, Ciccia, D'Haultfœuille &
Knau, arXiv:2405.04465): every group adopts at the same period F with a
heterogeneous dose, no group stays untreated, and the counterfactual is
the local polynomial intercept at dose zero supplied by *quasi-untreated*
groups.

Golden numbers from Stata 18 MP, generated by
``tests/stata_parity/option_parity/87_did_had.do`` with
``effects(3) placebo(2)``.

Two comparisons, deliberately
-----------------------------
``fitted`` feeds StatsPAI the bandwidths Stata *reports*, isolating the
estimator: a failure there cannot be a bandwidth difference.
``fitted_auto`` runs Stata's actual default path, selecting the bandwidth
per horizon with ``mse-dpi``. Keeping both means a regression can be
localized to the estimator or the selector without re-deriving anything.

Tolerance 1e-6; observed worst case 1.6e-8 with supplied bandwidths and
9.8e-8 end-to-end with selection, on all five horizons.

⚠️ The interval is not symmetric
--------------------------------
``did_had`` pairs the *conventional* point estimate with a
*bias-corrected* interval centred at ``β̂ − B̂``. A test asserting
``ci ≈ estimate ± z·se`` would fail against Stata, and should.

Regression history — tied doses
-------------------------------
The fixture deliberately contains 25 groups with dose exactly 0. In this
design that is the normal case, not a corner one: true stayers all sit at
the evaluation point. A plain k-NN variance picks an arbitrary subset of
the tie group and got the standard error wrong by **3–6%** while the
point estimate was still exact to 2e-9 — the kind of error that survives
review because the headline number is right. ``lprobust`` consumes tie
groups whole; ``test_ties_at_dose_zero_are_handled`` pins it.
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
import pandas as pd
import pytest

import statspai as sp

_HERE = pathlib.Path(__file__).resolve().parents[1] / "stata_parity" / "option_parity"
_DATA = _HERE / "data_87_did_had.csv"
_GOLDEN = _HERE / "results" / "87_did_had_Stata.json"

ATOL = 1e-6

# Stata row name -> StatsPAI relative time.
ROW_TO_HORIZON = {
    "Placebo_2": -2,
    "Placebo_1": -1,
    "Effect_1": 1,
    "Effect_2": 2,
    "Effect_3": 3,
}
# The order did_had reports: placebos furthest-first, then effects.
REPORT_ORDER = ["Placebo_2", "Placebo_1", "Effect_1", "Effect_2", "Effect_3"]


@pytest.fixture(scope="module")
def panel() -> pd.DataFrame:
    return pd.read_csv(_DATA)


@pytest.fixture(scope="module")
def golden() -> dict:
    return {
        k: v
        for k, v in json.loads(_GOLDEN.read_text(encoding="utf-8")).items()
        if not k.startswith("_")
    }


@pytest.fixture(scope="module")
def fitted(panel, golden):
    """Fit with Stata's own bandwidths, so only the estimator is compared."""
    return sp.did_had(
        panel,
        "y",
        "g",
        "t",
        "d",
        effects=3,
        placebo=2,
        bandwidth=[golden[k]["bw"] for k in REPORT_ORDER],
    )


@pytest.fixture(scope="module")
def fitted_auto(panel):
    """Stata's real default path: bandwidth selected per horizon."""
    return sp.did_had(panel, "y", "g", "t", "d", effects=3, placebo=2)


class TestBandwidthSelection:
    """mse-dpi end to end, which is what `did_had` does by default."""

    @pytest.mark.parametrize("row", REPORT_ORDER)
    def test_selected_bandwidth_matches_stata(self, fitted_auto, golden, row):
        h = ROW_TO_HORIZON[row]
        got = fitted_auto.detail.loc[
            fitted_auto.detail["relative_time"] == h, "bandwidth"
        ].iloc[0]
        assert got == pytest.approx(golden[row]["bw"], abs=ATOL)

    @pytest.mark.parametrize("row", REPORT_ORDER)
    @pytest.mark.parametrize("field,ref", [("estimate", "estimate"), ("se", "se")])
    def test_end_to_end_matches_stata(self, fitted_auto, golden, row, field, ref):
        h = ROW_TO_HORIZON[row]
        got = fitted_auto.detail.loc[
            fitted_auto.detail["relative_time"] == h, field
        ].iloc[0]
        assert got == pytest.approx(golden[row][ref], abs=ATOL)

    def test_bandwidth_varies_across_horizons(self, fitted_auto):
        """Each horizon is a different regression, so it gets its own h.

        A single bandwidth reused everywhere would still pass the
        supplied-bandwidth tests, and would be wrong.
        """
        assert fitted_auto.detail["bandwidth"].nunique() == len(REPORT_ORDER)

    def test_bias_bandwidth_is_h_not_the_selectors_b(self, panel):
        """lprobust's rho=1 sets b = h; the selector's own b is larger.

        On the lprobust fixture the selector reports b = 1.021 against
        h = 0.593. Using b would widen every bias-correction window and
        silently move tau_bc.
        """
        d = panel[panel["t"] == 4]
        bw = sp.lpbwselect_mse_dpi(d["d"].to_numpy(float), d["y"].to_numpy(float), 0.0)
        assert bw["b"] != bw["h"]

    def test_method_recorded(self, fitted_auto, fitted):
        assert fitted_auto.diagnostics["bandwidth_method"] == "mse-dpi"
        assert fitted.diagnostics["bandwidth_method"] == "supplied"

    def test_unknown_bandwidth_string_rejected(self, panel):
        with pytest.raises(ValueError, match="must be 'mse-dpi'"):
            sp.did_had(panel, "y", "g", "t", "d", effects=1, bandwidth="imse-dpi")


class TestDidHadParity:
    @pytest.mark.parametrize("row", REPORT_ORDER)
    @pytest.mark.parametrize(
        "ours,theirs",
        [
            ("estimate", "estimate"),
            ("se", "se"),
            ("ci_lower", "ci_lo"),
            ("ci_upper", "ci_hi"),
        ],
    )
    def test_cell_matches_stata(self, fitted, golden, row, ours, theirs):
        h = ROW_TO_HORIZON[row]
        got = fitted.detail.loc[fitted.detail["relative_time"] == h, ours].iloc[0]
        want = golden[row][theirs]
        assert got == pytest.approx(
            want, abs=ATOL
        ), f"{row}.{ours}: {got:.12f} vs Stata {want:.12f}"

    @pytest.mark.parametrize("row", REPORT_ORDER)
    def test_groups_inside_the_bandwidth_match(self, fitted, golden, row):
        """A discrete check that both sides used the same groups."""
        h = ROW_TO_HORIZON[row]
        got = fitted.detail.loc[fitted.detail["relative_time"] == h, "n_in_bw"].iloc[0]
        assert int(got) == golden[row]["n_in_bw"]

    def test_headline_is_effect_one(self, fitted, golden):
        assert fitted.estimate == pytest.approx(
            golden["Effect_1"]["estimate"], abs=ATOL
        )
        assert fitted.se == pytest.approx(golden["Effect_1"]["se"], abs=ATOL)

    def test_interval_is_bias_corrected_not_symmetric(self, fitted):
        """Pin the asymmetry rather than accidentally "fixing" it later."""
        row = fitted.detail[fitted.detail["relative_time"] == 1].iloc[0]
        centre = (row["ci_lower"] + row["ci_upper"]) / 2
        assert abs(centre - row["estimate"]) > 1e-6, (
            "the interval should be centred at estimate - bias, not at the "
            "estimate; if this passes the bias correction has been dropped"
        )
        assert centre == pytest.approx(row["estimate"] - row["bias"], abs=1e-12)


class TestQuasiUntreatedTest:
    def test_matches_stata(self, fitted, golden):
        row = fitted.detail[fitted.detail["relative_time"] == 1].iloc[0]
        assert row["qug_statistic"] == pytest.approx(
            golden["Effect_1"]["qug_t"], abs=1e-6
        )
        assert row["qug_pvalue"] == pytest.approx(golden["Effect_1"]["qug_p"], abs=1e-6)

    def test_identical_across_effects_when_treatment_changes_once(self, fitted):
        """The reference documents this as the diagnostic for a single switch."""
        eff = fitted.detail[fitted.detail["relative_time"] > 0]
        assert eff["qug_statistic"].nunique() == 1

    def test_closed_form(self):
        """T = D(1)/(D(2)-D(1)), p = 1/(1+T) — no bandwidth involved."""
        got = sp.quasi_untreated_test([0.2, 0.5, 1.0])
        assert got["statistic"] == pytest.approx(0.2 / 0.3)
        assert got["pvalue"] == pytest.approx(1 / (1 + 0.2 / 0.3))

    def test_a_dose_far_from_zero_rejects(self):
        """No credible quasi-untreated group => small p."""
        assert sp.quasi_untreated_test([5.0, 5.1, 6.0])["pvalue"] < 0.05

    def test_a_dose_near_zero_does_not_reject(self):
        assert sp.quasi_untreated_test([1e-4, 1.0, 2.0])["pvalue"] > 0.9

    def test_exact_zeros_are_excluded_as_stayers(self):
        """Zeros are genuine stayers; the statistic is about positive doses."""
        with_zeros = sp.quasi_untreated_test([0.0, 0.0, 0.2, 0.5])
        without = sp.quasi_untreated_test([0.2, 0.5])
        assert with_zeros == without

    def test_too_few_positive_doses_raises(self):
        with pytest.raises(ValueError, match="at least two distinct positive"):
            sp.quasi_untreated_test([0.0, 0.0, 1.0])


class TestMassPoints:
    def test_ties_at_dose_zero_are_handled(self, panel, fitted, golden):
        """⚠️ Regression: 25 tied zero doses moved the SE by 3-6%.

        The point estimate never noticed. Only the nearest-neighbour
        variance did, because a plain k-NN takes an arbitrary subset of a
        tie group where the reference takes it whole.
        """
        assert int((panel[panel["t"] == 4]["d"] == 0).sum()) == 25
        for row in REPORT_ORDER:
            h = ROW_TO_HORIZON[row]
            got = fitted.detail.loc[fitted.detail["relative_time"] == h, "se"].iloc[0]
            assert got == pytest.approx(golden[row]["se"], abs=ATOL)


class TestDidHadValidation:
    def test_staggered_adoption_is_rejected(self, panel):
        """This estimator is only valid with a common adoption date."""
        bad = panel.copy()
        late = bad["g"] % 2 == 1
        bad.loc[late & (bad["t"] == 4), "d"] = 0.0  # half the groups adopt at t=5
        with pytest.raises(ValueError, match="adopt at the SAME period"):
            sp.did_had(bad, "y", "g", "t", "d", effects=1, bandwidth=0.5)

    def test_too_many_effects_rejected(self, panel):
        with pytest.raises(ValueError, match="exceeds the .* estimable"):
            sp.did_had(panel, "y", "g", "t", "d", effects=9, bandwidth=0.5)

    def test_too_many_placebos_rejected(self, panel):
        with pytest.raises(ValueError, match="placebo=.* exceeds"):
            sp.did_had(panel, "y", "g", "t", "d", effects=1, placebo=9, bandwidth=0.5)

    def test_bandwidth_sequence_length_checked(self, panel):
        with pytest.raises(ValueError, match="horizons are"):
            sp.did_had(
                panel, "y", "g", "t", "d", effects=3, placebo=2, bandwidth=[0.5, 0.6]
            )

    @pytest.mark.parametrize("bad", [0.0, -1.0, np.nan])
    def test_invalid_bandwidth_rejected(self, panel, bad):
        with pytest.raises(ValueError, match="positive and finite"):
            sp.did_had(panel, "y", "g", "t", "d", effects=1, bandwidth=bad)

    def test_trends_lin_needs_three_pre_periods(self, panel):
        """Adoption at F=4 leaves periods 1-3, so this is allowed here."""
        res = sp.did_had(
            panel, "y", "g", "t", "d", effects=1, bandwidth=0.5, trends_lin=True
        )
        assert np.isfinite(res.estimate)

    def test_dynamic_uses_cumulative_dose(self, panel):
        """Cumulative normalization must differ from the static one at l > 1."""
        static = sp.did_had(panel, "y", "g", "t", "d", effects=2, bandwidth=0.5)
        dyn = sp.did_had(
            panel, "y", "g", "t", "d", effects=2, bandwidth=0.5, dynamic=True
        )
        s2 = static.detail[static.detail["relative_time"] == 2]["estimate"].iloc[0]
        d2 = dyn.detail[dyn.detail["relative_time"] == 2]["estimate"].iloc[0]
        assert abs(s2 - d2) > 1e-6


@pytest.fixture(scope="module")
def fitted_yatchew(panel):
    return sp.did_had(panel, "y", "g", "t", "d", effects=3, placebo=2, yatchew=True)


class TestYatchewTest:
    """Yatchew differencing test, as ``did_had ..., yatchew``.

    Theorem 5 of the paper: with (quasi-)untreated groups, plain OLS of
    the evolution on the dose is unbiased for the same estimand *iff*
    that conditional expectation is linear. So a non-rejection licenses
    the far simpler estimator.
    """

    @pytest.mark.parametrize("row", REPORT_ORDER)
    @pytest.mark.parametrize(
        "field,ref", [("statistic", "yatchew_t"), ("pvalue", "yatchew_p")]
    )
    def test_matches_stata(self, fitted_yatchew, golden, row, field, ref):
        h = ROW_TO_HORIZON[row]
        got = fitted_yatchew.detail.loc[
            fitted_yatchew.detail["relative_time"] == h, f"yatchew_{field}"
        ].iloc[0]
        assert got == pytest.approx(golden[row][ref], abs=1e-6)

    def test_effects_test_linearity_placebos_test_independence(self, panel):
        """The reference uses order 1 for effects and order 0 for placebos.

        The placebo null is not "linear in dose" — it is that the
        pre-period evolution does not depend on the FUTURE dose at all.
        Using order 1 there would test the wrong thing and still produce
        a plausible number.
        """
        d = panel[panel["t"].isin([3, 4])].sort_values(["g", "t"])
        dy = d.groupby("g")["y"].diff().dropna().to_numpy()
        dose = d[d["t"] == 4].sort_values("g")["d"].to_numpy()
        assert sp.yatchew_linearity_test(dose, dy, order=0)[
            "statistic"
        ] != pytest.approx(
            sp.yatchew_linearity_test(dose, dy, order=1)["statistic"], abs=1e-6
        )

    def test_absent_unless_requested(self, fitted):
        assert np.isnan(fitted.detail["yatchew_statistic"]).all()

    def test_truly_linear_data_is_not_rejected(self):
        rng = np.random.default_rng(5)
        x = rng.uniform(0, 1, 500)
        got = sp.yatchew_linearity_test(x, 2.0 * x + rng.normal(0, 0.1, 500))
        assert got["pvalue"] > 0.05

    def test_strong_curvature_is_rejected(self):
        """Power: a test that cannot see a quadratic is worthless here."""
        rng = np.random.default_rng(5)
        x = rng.uniform(0, 1, 500)
        got = sp.yatchew_linearity_test(x, 5.0 * x**2 + rng.normal(0, 0.05, 500))
        assert got["pvalue"] < 0.01

    def test_ties_are_broken_by_y(self):
        """⚠️ Regression: the differencing is over ADJACENT sorted rows.

        The reference sorts by x THEN y. Sorting by x alone left the
        statistic 0.36 away from Stata on the did_had fixture, because
        25 groups share dose exactly 0 and the order within that block
        changes every first difference through it.
        """
        x = np.array([0.0, 0.0, 0.0, 1.0, 2.0, 3.0])
        y = np.array([5.0, 1.0, 3.0, 4.0, 6.0, 8.0])
        by_xy = sp.yatchew_linearity_test(x, y, order=1)
        # same data, tie block presented in a different order
        perm = [2, 0, 1, 3, 4, 5]
        shuffled = sp.yatchew_linearity_test(x[perm], y[perm], order=1)
        assert by_xy["s2_diff"] == pytest.approx(
            shuffled["s2_diff"], abs=1e-12
        ), "s2_diff must not depend on the input order of tied x"

    def test_homoskedastic_variant_differs(self):
        rng = np.random.default_rng(7)
        x = rng.uniform(0, 1, 300)
        y = 2 * x + rng.normal(0, 0.2, 300)
        assert sp.yatchew_linearity_test(x, y, het_robust=True)[
            "statistic"
        ] != pytest.approx(
            sp.yatchew_linearity_test(x, y, het_robust=False)["statistic"], abs=1e-9
        )

    def test_mismatched_lengths_rejected(self):
        with pytest.raises(ValueError, match="same length"):
            sp.yatchew_linearity_test(np.arange(10.0), np.arange(9.0))

    def test_too_few_observations_rejected(self):
        with pytest.raises(ValueError, match="at least 3"):
            sp.yatchew_linearity_test([1.0, 2.0], [1.0, 2.0])
