"""Track C performance comparator.

Joins per-estimator timings on the StatsPAI and declared reference sides, emits a
Markdown rollup, a LaTeX table for §6 of the manuscript, and a
log-log scaling figure.
"""

from __future__ import annotations

import json
import math
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # _figstyle.py sits here

import matplotlib  # noqa: E402  (after the sys.path insert above)

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from _figstyle import TEXT_WIDTH_IN  # noqa: E402
from _figstyle import apply as _apply_figstyle  # noqa: E402
from matplotlib.ticker import (  # noqa: E402
    FixedLocator,
    FuncFormatter,
    LogLocator,
    NullFormatter,
)

_apply_figstyle(plt)

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
RESULTS_DIR = HERE / "results"
FIGURES_DIR = HERE / "figures"
PAPER_TABLES_DIR = ROOT / "Paper-JSS" / "manuscript" / "tables"
PAPER_FIGURES_DIR = ROOT / "Paper-JSS" / "manuscript" / "figures"
PDF_METADATA = {"CreationDate": None}
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
PAPER_TABLES_DIR.mkdir(parents=True, exist_ok=True)
PAPER_FIGURES_DIR.mkdir(parents=True, exist_ok=True)


ESTIMATORS = {
    "01_hdfe": {
        "name": "HDFE 2-way FE",
        "ref": "fixest::feols",
        "ref_side": "R",
        "x_label": "N (observations)",
    },
    "02_csdid": {
        "name": "CS-DiD simple ATT",
        "ref": "did::att_gt",
        "ref_side": "R",
        "x_label": "N (observations)",
    },
    "03_scm": {
        "name": "Classical SCM",
        "ref": "Synth::synth",
        "ref_side": "R",
        "x_label": "n_donors",
    },
    "04_dml": {
        "name": "DML PLR (lin. learners)",
        "ref": "doubleml-for-py",
        "ref_side": "doubleml_py",
        "x_label": "N (observations)",
    },
}


def load(estimator: str, side: str) -> list[dict]:
    path = RESULTS_DIR / f"{estimator}_{side}.json"
    if not path.exists():
        return []
    return json.loads(path.read_text())["rows"]


def measured_versions() -> list[str]:
    """StatsPAI versions recorded by the Python-side result files.

    Older files predate the field and contribute "unrecorded"; a table
    built from them should say so rather than imply the current release.
    """
    versions = set()
    for est, cfg in ESTIMATORS.items():
        path = RESULTS_DIR / f"{est}_py.json"
        if not path.exists():
            continue
        hw = json.loads(path.read_text()).get("hardware") or {}
        versions.add(hw.get("statspai_version") or "unrecorded")
    return sorted(versions)


def render_md() -> str:
    lines: list[str] = [
        "# Track C performance report",
        "",
        "Generated by `tests/perf/compare_perf.py`. Hardware:",
        "Apple Silicon arm64, 8 physical cores, 24 GB RAM, macOS 26.",
        "",
        "Each row reports the median wall-clock time across 3 or 5 reps "
        "after a warmup. "
        "The ratio is `reference_time / sp_time` (>1 means sp is faster).",
        "",
    ]
    for est, cfg in ESTIMATORS.items():
        py = load(est, "py")
        r = load(est, cfg["ref_side"])
        if not py or not r:
            continue
        lines.append(f"## {est}: {cfg['name']}")
        lines.append("")
        lines.append(f"| n | sp (s) | {cfg['ref']} (s) | ratio ref/sp |")
        lines.append("|---:|---:|---:|---:|")
        r_by_n = {row["n"]: row for row in r}
        for prow in py:
            rrow = r_by_n.get(prow["n"])
            ratio = (
                rrow["median_time_s"] / prow["median_time_s"]
                if rrow and prow["median_time_s"] > 0
                else None
            )
            ratio_s = f"{ratio:.2f}" if ratio is not None else "—"
            lines.append(
                f"| {prow['n']} | {prow['median_time_s']:.4f} | "
                f"{rrow['median_time_s']:.4f} | {ratio_s} |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def _tex(text: str) -> str:
    """Escape a display label for LaTeX.

    ``ESTIMATORS`` holds plain text because the same strings are drawn by
    Matplotlib, which prints a backslash literally: pre-escaping them put
    ``did::att\\_gt`` and ``n\\_donors`` into the published Figure 3 axes.
    Escaping happens here, at the one boundary that needs it.
    """
    return text.replace("\\", "\\textbackslash{}").replace("_", "\\_")


def render_tex() -> str:
    rows: list[str] = []
    ref_tex = {
        "fixest::feols": "\\pkg{fixest}",
        "did::att_gt": "\\pkg{did}",
        "Synth::synth": "\\pkg{Synth}",
        "DoubleML::DoubleMLPLR": "\\pkg{DoubleML}",
        "doubleml-for-py": "\\pkg{DoubleML} Python",
    }
    for est, cfg in ESTIMATORS.items():
        py = load(est, "py")
        r = load(est, cfg["ref_side"])
        if not py or not r:
            continue
        r_by_n = {row["n"]: row for row in r}
        ratios = []
        for prow in py:
            rrow = r_by_n.get(prow["n"])
            if rrow and prow["median_time_s"] > 0:
                ratios.append(rrow["median_time_s"] / prow["median_time_s"])
        if not ratios:
            continue
        max_n = max(prow["n"] for prow in py)
        last = next(p for p in py if p["n"] == max_n)
        last_r = r_by_n.get(max_n, {}).get("median_time_s", float("nan"))
        ratio_max = (
            last_r / last["median_time_s"] if last["median_time_s"] > 0 else None
        )
        ratio_str = (
            f"sp $\\mathbf{{{ratio_max:.1f}\\times}}$"
            if ratio_max and ratio_max > 1.5
            else (
                f"R $\\mathbf{{{1/ratio_max:.1f}\\times}}$"
                if ratio_max and ratio_max < 0.67
                else f"tie ${ratio_max:.2f}\\times$"
            )
        )
        est_tex = _tex(est)
        max_n_tex = f"{max_n:,}".replace(",", "{,}")
        rows.append(
            f"\\code{{{est_tex}}} & {cfg['name']} & "
            f"{ref_tex.get(cfg['ref'], _tex(cfg['ref']))} & {max_n_tex} & "
            f"{last['median_time_s']:.3f} & {last_r:.3f} & {ratio_str} \\\\"
        )
    body = "\n".join(rows)
    return (
        "% AUTO-GENERATED by tests/perf/compare_perf.py\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\begingroup\n"
        "\\footnotesize\n"
        "\\setlength{\\tabcolsep}{2pt}\n"
        "\\begin{tabular}{@{}p{0.10\\linewidth}p{0.20\\linewidth}"
        "p{0.13\\linewidth}r r r p{0.14\\linewidth}@{}}\n"
        "\\toprule\n"
        "Module & Estimator & Reference & Max. $N$ & sp & Ref. & Faster path \\\\\n"
        "\\midrule\n"
        f"{body}\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\endgroup\n"
        "\\caption{Track C measured performance on Apple Silicon arm64 / "
        "8 cores / 24~GB, "
        f"\\statspai{{}} {' / '.join(measured_versions())}. "
        "Times are median seconds at the largest sample size, "
        "across 3 or 5 repetitions after one warmup, "
        "using seed-fixed DGPs. Bold denotes a gap of at least $1.5\\times$. "
        "The DML row uses \\pkg{DoubleML} Python with the same linear learners, "
        "five folds, and public-workflow construction cost. "
        "The Callaway--Sant'Anna row uses "
        "a homogeneous-effect DGP favourable to the vectorised group-time loop.}\n"
        "\\label{tab:track-c-perf}\n"
        "\\end{table}\n"
    )


def render_figure() -> Path:
    # Drawn at the printed width so the point sizes in _figstyle are the
    # point sizes on the page; \includegraphics uses width=\textwidth.
    fig, axes = plt.subplots(2, 2, figsize=(TEXT_WIDTH_IN, 0.78 * TEXT_WIDTH_IN))
    for ax, (est, cfg) in zip(axes.flat, ESTIMATORS.items()):
        py = load(est, "py")
        r = load(est, cfg["ref_side"])
        if not py or not r:
            ax.text(0.5, 0.5, "no data", ha="center", va="center")
            continue
        py_n = [row["n"] for row in py]
        py_t = [row["median_time_s"] for row in py]
        r_n = [row["n"] for row in r]
        r_t = [row["median_time_s"] for row in r]
        ax.loglog(py_n, py_t, "o-", label="StatsPAI", linewidth=2, markersize=8)
        ax.loglog(r_n, r_t, "s--", label=cfg["ref"], linewidth=2, markersize=7)
        # Pad every y-range out to full decades so each panel shows the
        # same 10^k tick style (a sub-decade range otherwise falls back
        # to linear-looking minor labels under a log-log title).
        lo = min(py_t + r_t)
        hi = max(py_t + r_t)
        ax.set_ylim(10 ** math.floor(math.log10(lo)), 10 ** math.ceil(math.log10(hi)))
        # Decade ticks on the time axis. Left to itself, Matplotlib
        # labels minor ticks whenever a log axis spans few decades, so
        # the DML panel printed 2x10^-3 ... 6x10^-3 while its three
        # neighbours printed 10^-3 ... 10^0: four panels under one
        # "log-log" heading with two different tick vocabularies.
        ax.yaxis.set_major_locator(LogLocator(base=10.0))
        ax.yaxis.set_minor_formatter(NullFormatter())
        # The size axis is ticked at the measured design points rather
        # than at decades. Two of the four benchmarks are sampled off
        # the decade grid (N = 5,000/25,000/125,000 and n = 20/50/100),
        # and decade-only ticks left the SCM panel with a single labelled
        # x value -- an axis a reader cannot read a size off.
        sizes = sorted({row["n"] for row in py} | {row["n"] for row in r})
        ax.xaxis.set_major_locator(FixedLocator(sizes))
        ax.xaxis.set_minor_locator(FixedLocator([]))
        ax.xaxis.set_major_formatter(FuncFormatter(lambda v, _pos: f"{int(v):,}"))
        ax.set_xlabel(cfg["x_label"])
        ax.set_ylabel("median wall-clock (s)")
        ax.set_title(f"{est}: {cfg['name']}")
        ax.grid(True, which="both", alpha=0.3, linewidth=0.4)
        ax.legend()
    # No suptitle: the hardware line and the "log-log scaling" framing
    # both live in the LaTeX caption, and repeating them inside the
    # graphic wastes two lines of the panel area at print size.
    fig.tight_layout()
    out = FIGURES_DIR / "track_c_loglog.pdf"
    fig.savefig(out, bbox_inches="tight", metadata=PDF_METADATA)
    fig.savefig(FIGURES_DIR / "track_c_loglog.png", bbox_inches="tight", dpi=150)
    plt.close(fig)
    shutil.copyfile(out, PAPER_FIGURES_DIR / "track_c_loglog.pdf")
    shutil.copyfile(
        FIGURES_DIR / "track_c_loglog.png", PAPER_FIGURES_DIR / "track_c_loglog.png"
    )
    return out


def main() -> None:
    md = render_md()
    tex = render_tex()
    (RESULTS_DIR / "perf_table.md").write_text(md, encoding="utf-8")
    (RESULTS_DIR / "perf_table.tex").write_text(tex, encoding="utf-8")
    (PAPER_TABLES_DIR / "track_c_perf.tex").write_text(tex, encoding="utf-8")
    fig = render_figure()
    print(
        "OK -- wrote perf_table.{md,tex}, "
        "Paper-JSS/manuscript/tables/track_c_perf.tex, and "
        f"{fig.name}"
    )


if __name__ == "__main__":
    main()
