# ---------------------------------------------------------------------------
# Generate the R reference fixture for sp.overlap_weights, for
# tests/reference_parity/test_overlap_weights_r_parity.py
#
# Requires: R >= 4.5 + WeightIt (>= 1.7.0).
# Run:      Rscript _generate_overlap_weights_R.R   (from this directory)
#
# What is pinned
# --------------
# Overlap weights (Li, Morgan & Zaslavsky 2018) give every unit the weight of
# the *opposite* arm's propensity:
#
#     w_i = 1 - e_i   for treated,      w_i = e_i   for control
#
# so units in the region of good overlap dominate and the estimand is the ATO.
# `WeightIt::weightit(..., method = "glm", estimand = "ATO")` fits the same
# logistic propensity model and applies the same transformation, so the two
# implementations should agree to the precision of the two logit solvers.
#
# The fixture also carries the ATE / ATT / ATC weighting schemes from the same
# generalized family (Li, Li & Li 2019, Table 1), because they share the
# propensity fit: if the ATO row agreed but the others did not, the agreement
# would be about the weight formula rather than the propensity model.
#
# Produces
# --------
#   overlap_weights_data.csv   id y d x1 x2
#   overlap_weights_R.json     per-estimand weights (per row) + effect
# ---------------------------------------------------------------------------
suppressMessages(library(WeightIt))
suppressMessages(library(jsonlite))

set.seed(20260807)
n  <- 400
x1 <- rnorm(n)
x2 <- rnorm(n)
d  <- rbinom(n, 1, plogis(0.9 * x1 - 0.5 * x2 - 0.2))
y  <- 1 + 2 * d + 0.7 * x1 - 0.3 * x2 + rnorm(n, sd = 0.5)
df <- data.frame(id = seq_len(n), y = y, d = d, x1 = x1, x2 = x2)

write.csv(df, "overlap_weights_data.csv", row.names = FALSE)

# The propensity model both sides fit.
ps_fit <- glm(d ~ x1 + x2, data = df, family = binomial())
ps     <- as.numeric(predict(ps_fit, type = "response"))

out <- list(
  `_source` = paste0(
    "R ", as.character(getRversion()),
    " + WeightIt ", as.character(packageVersion("WeightIt")),
    ", generated by _generate_overlap_weights_R.R"
  ),
  `_note` = paste0(
    "Overlap (ATO) weights are 1-e for treated and e for control ",
    "(Li, Morgan & Zaslavsky 2018). WeightIt fits the same glm propensity ",
    "model, so agreement is bounded by the two logit solvers, not by the ",
    "weighting scheme."
  ),
  ps_logit_coef = as.list(coef(ps_fit)),
  pscore = ps
)

for (est in c("ATO", "ATE", "ATT", "ATC")) {
  w  <- weightit(d ~ x1 + x2, data = df, method = "glm", estimand = est)
  ww <- as.numeric(w$weights)
  eff <- weighted.mean(df$y[df$d == 1], ww[df$d == 1]) -
         weighted.mean(df$y[df$d == 0], ww[df$d == 0])
  out[[est]] <- list(
    weights = ww,
    effect  = eff,
    sum_w_treated = sum(ww[df$d == 1]),
    sum_w_control = sum(ww[df$d == 0])
  )
  cat(sprintf("%-4s effect = %.16e   sum_w = %.10f\n", est, eff, sum(ww)))
}

write(toJSON(out, digits = NA, auto_unbox = TRUE, pretty = TRUE),
      "overlap_weights_R.json")
cat("wrote overlap_weights_data.csv + overlap_weights_R.json\n")
