*! _generate_truncreg_vce_Stata.do
*! Frozen Stata 18 truncreg covariance matrices for
*! tests/reference_parity/test_truncreg_vce_parity.py
*!
*! Data: tests/r_parity/data/62_truncreg.csv (read as double), clusters
*! cl = mod(_n - 1, 50).  Writes truncreg_vce_Stata.txt next to this file:
*! one "tag value" line per number, b then vec(V) for vce(oim),
*! vce(robust) and vce(cluster cl).  Coefficient order x1 x2 _cons sigma.
*!
*!   stata -b do tests/reference_parity/_fixtures/_generate_truncreg_vce_Stata.do
set type double
import delimited using "tests/r_parity/data/62_truncreg.csv", clear asdouble
gen long cl = mod(_n - 1, 50)
quietly truncreg y x1 x2, ll(0)
matrix b0 = e(b)
matrix V0 = e(V)
quietly truncreg y x1 x2, ll(0) vce(robust)
matrix Vr = e(V)
quietly truncreg y x1 x2, ll(0) vce(cluster cl)
matrix Vc = e(V)
mata:
b = st_matrix("b0"); V0 = st_matrix("V0"); Vr = st_matrix("Vr"); Vc = st_matrix("Vc")
_unlink("tests/reference_parity/_fixtures/truncreg_vce_Stata.txt")
fh = fopen("tests/reference_parity/_fixtures/truncreg_vce_Stata.txt", "w")
fput(fh, "* Stata " + strofreal(c("stata_version")) + " truncreg, generated by _generate_truncreg_vce_Stata.do")
for (i = 1; i <= cols(b); i++) fput(fh, sprintf("b %21.17g", b[1, i]))
for (i = 1; i <= 16; i++) fput(fh, sprintf("V0 %21.17g", vec(V0)[i]))
for (i = 1; i <= 16; i++) fput(fh, sprintf("Vr %21.17g", vec(Vr)[i]))
for (i = 1; i <= 16; i++) fput(fh, sprintf("Vc %21.17g", vec(Vc)[i]))
fclose(fh)
end
